apache/zeppelin

- docs/interpreter/neo4j.md
- neo4j/pom.xml
- neo4j/src/main/java/org/apache/zeppelin/graph/neo4j/Neo4jCypherInterpreter.java
- neo4j/src/test/java/org/apache/zeppelin/graph/neo4j/Neo4jCypherInterpreterTest.java
Add the support for Point and Date data types introduced since Neo4j 3.4
[Improvement] In order to allow users to use the Neo4j Interpreter with the last introduced Data types
* Put link here, and add [ZEPPELIN-3882](https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-3882)
* Execute the unit tests
* Does the licenses files need update? no
> [ZEPPELIN-3882] Neo4jInterpreter - Support Point and Date Types

- scripts/docker/spark-cluster-managers/spark_mesos/Dockerfile
- scripts/docker/spark-cluster-managers/spark_mesos/entrypoint.sh
In the [spark_mesos example - Dockerfile](https://github.com/apache/zeppelin/blob/master/scripts/docker/spark-cluster-managers/spark_mesos/Dockerfile), there are some issues.
1. The original used SPARK_VERSION=2.1.2 is not available now, update it to 2.4.0
2. There is no package named libevent2-devel, it should be corrected to libevent-devel
3. Update from centos6 to centos7
4. Update from jdk7 to jdk8
In the [spark_mesos example - entrypoint.sh](https://github.com/apache/zeppelin/blob/master/scripts/docker/spark-cluster-managers/spark_mesos/entrypoint.sh):
1. Follow the instructions: [zeppelin on spark mesos mode - configure spark interpreter in zeppelin](https://zeppelin.apache.org/docs/0.8.0/setup/deployment/spark_cluster_mode.html#4-configure-spark-interpreter-in-zeppelin-1) add the …
> [ZEPPELIN-3932] spark_mesos Dockerfile should be updated

- zeppelin-server/src/main/java/org/apache/zeppelin/realm/ActiveDirectoryGroupRealm.java
ActiveDirectoryGroupRealm is using UserPrincipalName for finding user and deriving groups that he belongs to. However this is not mandatory nor always corresponds to the REALM that user belongs to.
This PR changed userPrincipalName to sAMAccountName when deriving groups user belongs to
[Bug Fix]
* [ZEPPELIN-3875](https://issues.apache.org/jira/browse/ZEPPELIN-3875)
* CI pass
* Does the licenses files need update? no
> [ZEPPELIN-3875] Groups are not derived when using ActiveDirectory

- scripts/docker/spark-cluster-managers/spark_mesos/Dockerfile
- scripts/docker/spark-cluster-managers/spark_standalone/Dockerfile
- scripts/docker/spark-cluster-managers/spark_yarn_cluster/Dockerfile
Upgrade the Dockerfiles of spark_standalone and spark_yarn_cluster to CentOS7 and Spark 2.4.0.
Java remains in version 7 since hadoop 2.x depends on Java7.
Improvement
* [ZEPPELIN-3944](https://issues.apache.org/jira/browse/ZEPPELIN-3944)
* Follow the instructions here: [spark-standalone](https://zeppelin.apache.org/docs/0.8.0/setup/deployment/spark_cluster_mode.html#spark-standalone-mode) and [spark-yarn-cluster](https://zeppelin.apache.org/docs/0.8.0/setup/deployment/spark_cluster_mode.html#spark-on-yarn-mode)
> [ZEPPELIN-3944] Update Dockerfiles of spark_standalone and spark_yarn_cluster

- zeppelin-web/src/app/visualization/builtins/visualization-table.js
Add button to drop-down list in visualization table to copy column name.
I know that column name could be obtained in a different way, for example, by auto-complete.
Nevertheless I think this feature is comfortable.
Feature
[ZEPPELIN-3575](https://issues.apache.org/jira/browse/ZEPPELIN-3575)
* Manually
> [ZEPPELIN-3575] Add 'Copy Column Name' to table visualisation-table 

- docs/security/shiroauthentication.md
spacing of "```" block causing it to be ignored, and the rest of the contents to be rendered incorrectly.
The LDAP section of the documentation for zeppelin-0.7.3 renders incorrectly, here:
http://zeppelin.apache.org/docs/0.7.3/security/shiroauthentication.html
It looks correct on GitHub, but not on the standalone site. This should fix it.
[Documentation | Bug Fix]
* none created
* no code to test - string/documentation formatting change only
* Does the licenses files need update? no
* Is there breaking changes for older versions? none known
> formatting fix for LDAP realm documentation

- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Note.java
Now note may move to the root directory after enabling cron in it. It caused by `Note#setName`
* Bug:
* Fix:
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-4011
* CI pass
> [ZEPPELIN-4011] Fix note path

- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
Paragraphs in cloned note disappear after zeppelin restart if they weren't executed
* Bug:
* Fix:
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-4012
* CI pass
> [ZEPPELIN-4012] Save paragraphs after clone

- spark/interpreter/pom.xml
- zeppelin-distribution/src/bin_license/LICENSE
This is to bump up version of org.jsoup:jsoup.
[Improvement]
* [ZEPPELIN-4186](https://jira.apache.org/jira/browse/ZEPPELIN-4186)
* CI should be green
* Does the licenses files need update? yes
* Is there breaking changes for older versions? n/a
* Does this needs documentation? n/a
> [ZEPPELIN-4186] Bump up version of org.jsoup:jsoup

- zeppelin-interpreter/src/test/java/org/apache/zeppelin/dep/DependencyResolverTest.java
Travis CI is failing with "DependencyResolverTest.testLoad:92 Â» Repository Cannot fetch dependencies for ..."
This is to temporarily disable that test until http://oss.sonatype.org/content/repositories/agimatec-releases/com/agimatec/agimatec-validation/0.9.3/agimatec-validation-0.9.3.jar is back online.
Another way to check if the above repo is up/down is the command below
```
mvn dependency:get -DgroupId=com.agimatec -DartifactId=agimatec-validation  -Dversion=0.9.3 -DrepoUrl=http://oss.sonatype.org/content/repositories/agimatec-releases/
```
[Hot Fix]
* [ZEPPELIN-4192](https://issues.apache.org/jira/browse/ZEPPELIN-4192)
* CI should be green
* Does the licenses files need update? N/A
* Is there breaking changes for older versions? N/A
* Does this needs documentation? N/A
> [ZEPPELIN-4192] Travis CI fails for dependency download

- zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/ParametersRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookRestApiTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/ZeppelinRestApiTest.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Note.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/CronJob.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
This PR add params to note run rest api, so that user can specify params for each note run. E.g. user can specify the date to run regular ETL job.
[Feature ]
* https://issues.apache.org/jira/browse/ZEPPELIN-4924
* Unit test is added in `NotebookRestApiTest`
> [ZEPPELIN-4924]. Add params to note run rest api

- docs/interpreter/flink.md
- flink/flink-scala-parent/src/main/resources/interpreter-setting.json
- flink/flink-scala-parent/src/main/scala/org/apache/zeppelin/flink/FlinkScalaInterpreter.scala
- flink/flink-scala-parent/src/test/resources/log4j.properties
- flink/flink-scala-parent/src/test/resources/log4j2.properties
- zeppelin-plugins/launcher/flink/src/main/java/org/apache/zeppelin/interpreter/launcher/FlinkInterpreterLauncher.java
This PR is to unify the configuration of flink interpreter. Due to historical reason, some properties are only available for yarn mode, but not for yarn-application mode, this PR is to unify them. Here's the properties we handle in this PR.
* flink.tm.memory
* flink.jm.memory
* flink.yarn.appName
* flink.yarn.queue
* flink.tm.slot
[Improvement]
* https://issues.apache.org/jira/browse/ZEPPELIN-5423
* CI pass
* 
> [ZEPPELIN-5428] Unify flink configuration between different execution modes

- python/src/main/java/org/apache/zeppelin/python/PythonInterpreter.java
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/PySparkInterpreter.java
- spark/interpreter/src/test/java/org/apache/zeppelin/spark/IPySparkInterpreterTest.java
- zeppelin-jupyter-interpreter/src/main/java/org/apache/zeppelin/jupyter/JupyterKernelInterpreter.java
2 changes here in this PR:
* Use SparkConf instead of properties, because the spark configuration may be in spark side (e.g. spark-defaults.conf instead of zeppelin side), `properties` mean the configuration in zeppelin side, `SparkConf` is the complete configuration of spark.
* Code improvement on the logics of detecting availability of IPython.
[Bug Fix | Improvement ]
* https://issues.apache.org/jira/browse/ZEPPELIN-5417
* Manually tested
* 
> [ZEPPELIN-5417] Unable to set conda env in pyspark

- docs/usage/rest_api/notebook.md
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/NewNoteRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookRestApiTest.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
This PR is to provide restful API to clone a specific revision of a note.
Here is one of usage scenarios:
Some time we need to run multiple version of a note independently.  
The easiest to copy the version of the note to a new note then run it.
It's helpful if there is a restful api to copy specific version of note.
[Feature]
* Open an issue on Jira https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-5661
* CI passed
> [ZEPPELIN-5661] Support clone a specific revision of a note

- sap/src/main/java/org/apache/zeppelin/sap/universe/UniverseClient.java
[Bug Fix | Improvement | Feature | Documentation | Hot Fix | Refactoring]
* https://issues.apache.org/jira/browse/ZEPPELIN-5665
> [ZEPPELIN-5665] rework xml factory

- .github/workflows/core.yml
Trivial PR to split spark-integration-test to hadoop2 and hadoop3
[Improvement ]
* https://issues.apache.org/jira/browse/ZEPPELIN-5671
* CI pass
> [ZEPPELIN-5671] Split spark-integration-test to hadoop2 and hadoop3

- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/HadoopUtils.java
- flink/flink-scala-parent/src/main/scala/org/apache/zeppelin/flink/FlinkScalaInterpreter.scala
- flink/flink-scala-parent/src/main/scala/org/apache/zeppelin/flink/internal/FlinkShell.scala
This PR is to delete the staging directory on hdfs for flink's yarn-application mode.
[ Improvement ]
* https://issues.apache.org/jira/browse/ZEPPELIN-5620
* Manually tested
> [ZEPPELIN-5620] Staging directory is not deleted in Flink's yarn-application

- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/ApplicationModeExecutionEnvironment.java
- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/ApplicationModeStreamEnvironment.java
- flink/flink-scala-parent/src/main/scala/org/apache/zeppelin/flink/FlinkScalaInterpreter.scala
The cause is that in the `yarn-application`, `StreamExecutionEnvironment#execute(StreamGrpah)` is invoked when calling `TableEnvironment#execute.` But we didn't override it before this PR, so the scala shell jar is not added into the flink job. 
This PR fix this issue by overriding the method `StreamExecutionEnvironment#execute(StreamGrpah)`
[Bug Fix]
* https://issues.apache.org/jira/browse/ZEPPELIN-5678
* Ci pass
* Is there breaking changes for older versions? NO
> [ZEPPELIN-5678] Remove the wordcount init job in Flink yarn-application mode

- spark/interpreter/src/main/java/org/apache/zeppelin/spark/SparkInterpreter.java
- spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkInterpreterTest.java
- spark/scala-2.11/src/main/scala/org/apache/zeppelin/spark/SparkScala211Interpreter.scala
- spark/scala-2.12/src/main/scala/org/apache/zeppelin/spark/SparkScala212Interpreter.scala
- spark/spark-scala-parent/src/main/scala/org/apache/zeppelin/spark/BaseSparkScalaInterpreter.scala
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterServer.java
- zeppelin-interpreter/src/test/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterServerTest.java
Optimize the interpreter execution process from the following aspects:
1. Close the interpreter executor thread when restart interpreter;
2. Only close opened interpreter when restart interpreter and create non-existent interpreter when create Interpreter;
3. For spark interpreter, reuse the static innerScalaInterpreter class, in the context of multi sub threads, which is only loaded by the first interpreter;
4. When close spark interpreter, set the inner objects (SparkZeppelinContext and sparkILoop) to empty.
[Improvement]
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5644
* Covered by existing unit test
> [ZEPPELIN-5644] Reduce redundancy during the interpreter execution process

- scalding/pom.xml
- submarine/pom.xml
- zeppelin-plugins/launcher/docker/pom.xml
use jinjava 2.5.4 due to cves
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN/ZEPPELIN-5690
> ZEPPELIN-5690: use jinjava 2.5.4 due to cves

- docs/interpreter/flink.md
- flink/flink-scala-parent/src/main/resources/interpreter-setting.json
- flink/flink-scala-parent/src/main/scala/org/apache/zeppelin/flink/internal/FlinkILoop.scala
Add one configuration `flink.scala_shell.tmp_dir` for configuring the tmp folder for flink scala shell compiled jars.
[Feature]
* https://issues.apache.org/jira/browse/ZEPPELIN-5621
* CI pass
> [ZEPPELIN-5621] add configuration of tmp_path to store compiled files like scala_shell_tmp-xxx.jar

- spark/interpreter/src/main/java/org/apache/zeppelin/spark/SparkSqlInterpreter.java
Trivial PR to reset the ClassLoader for the correct scala version
[Bug Fix ]
* https://issues.apache.org/jira/browse/ZEPPELIN-5705
> [ZEPPELIN-5705] Incorrect scala version checking in SparkSqlInterpreter.java

- docs/interpreter/flink.md
- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/FlinkBatchSqlInterpreter.java
- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/FlinkInterpreter.java
- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/FlinkStreamSqlInterpreter.java
- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/IPyFlinkInterpreter.java
- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/PyFlinkInterpreter.java
- flink/flink-scala-parent/src/main/resources/python/zeppelin_ipyflink.py
- flink/flink-scala-parent/src/main/resources/python/zeppelin_pyflink.py
- flink/flink-scala-parent/src/main/scala/org/apache/zeppelin/flink/FlinkScalaInterpreter.scala
The old planner is removed starting from Flink 1.14. It is only used by a few users in some uncommon scenarios. This PR is to remove it from Flink interpreter to reduce maintenance effort.
[ Improvement ]
* https://issues.apache.org/jira/browse/ZEPPELIN-5697
* CI 
> [ZEPPELIN-5697] Remove old planner support of flink

- spark/interpreter/src/main/java/org/apache/zeppelin/spark/SparkSqlInterpreter.java
- spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkInterpreterTest.java
- spark/scala-2.12/src/main/scala/org/apache/zeppelin/spark/SparkScala212Interpreter.scala
- spark/scala-2.13/src/main/scala/org/apache/zeppelin/spark/SparkScala213Interpreter.scala
Setting thread context classloader of interpreter thread before creating SparkContext object in order to preserve correct classloader hierarchy.
We worked out this patch for fixing ZEPPELIN-4627, and it also seems to fix ZEPPELIN-5688.
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-4627
* https://issues.apache.org/jira/browse/ZEPPELIN-5688
* Manually tested cases described in ZEPPELIN-4627
* Added unit test for cases described in ZEPPELIN-5688
> [ZEPPELIN-4627] Fix class loader inconsistency between driver and executor when running on Spark 3.x

- cassandra/pom.xml
Hi, @corneadoug, @Reamer , I'd like to report a vulnerability dependency in **org.apache.zeppelin:zeppelin-cassandra:0.10.1**.
I noticed that **org.apache.zeppelin:zeppelin-cassandra:0.10.1** directly depends on **org.lz4:lz4-java:1.6.0** in the [pom](https://repo1.maven.org/maven2/org/apache/zeppelin/zeppelin-cassandra/0.10.1/zeppelin-cassandra-0.10.1.pom). However, as shown in the following dependency graph, **org.lz4:lz4-java:1.6.0** sufferes from the vulnerabilites which the C library **lz4(version:1.9.1)** exposed, containing a high severity CVE: [CVE-2019-17543](https://nvd.nist.gov/vuln/detail/CVE-2019-17543).
**org.lz4:lz4-java:1.7.0** (**>=1.7.0**) has upgraded the vulnerable C library `lz4` to the patch version **1.9.2**. 
Java build tools cannot report vulnerable C libraries, …
> Potential security vulnerability in the lz4 C library.

- zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
For user under runner role, the editor is hidden, so the **$scope.editor object** is not empty and the **$scope.editor.getValue()** function may return a null value.
So there should be one more condition to judge: if user cannot view editor, it's also expected to get editor value from **$scope.paragraph.text** as well.
The **$scope.viewOnly** in notebook.controller.js determines whether the editor is editable for user, and when user is under role of owner or writer, the value will become true. This value can be referred in the adjacent js files. 
So it's used as a new judgement condition when get editor value.
Bug Fix 
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5717
* Create paragraph with input box in notebook;
* Grant one user with only runner role;
* Login …
> [ZEPPELIN-5717] Fix incorrect editor value gotten by Runner

- zeppelin-client-examples/src/main/java/org/apache/zeppelin/client/examples/ZeppelinClientExample.java
- zeppelin-client/src/main/java/org/apache/zeppelin/client/ZeppelinClient.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookRestApiTest.java
Currently there's a cancelParagraph method in zeppelin client api, however, there's no cancelNote method.
PR is to add a cancelNote method  in zeppelin client api.
Improvement
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5728
* CI passed
> [ZEPPELIN-5728] Absence of cancelNote method in Zeppelin Client Api

- docs/interpreter/hive.md
- docs/interpreter/jdbc.md
- jdbc/src/main/java/org/apache/zeppelin/jdbc/JDBCInterpreter.java
- jdbc/src/main/resources/interpreter-setting.json
This PR introduce a JDBC interpreter property for disable setting tag for application of hive engines.
Some users disabled tez.* property in hive  and hence unable to use hive in zeppelin. The reason is Zeppelin jdbc interpreter always set both tez and MR tags property when connect to hive.   This PR provide a property to disable setting tag for tez and MR application in hive.
Improvement
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5614
* CI passed
> [ZEPPELIN-5614] A JDBC interpreter property for disable setting tag for application of hive engines

- conf/zeppelin-site.xml.template
- docs/setup/operation/configuration.md
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java
The default value of zeppelin.interpreter.connect.timeout is 60 seconds. This is too small in the case of running spark in yarn-cluster mode. 
BTY, in docs, the description for this property is wrong.
Improvement
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5729
* CI Passed
> [ZEPPELIN-5729] Increase default value of zeppelin.interpreter.connect.timeout

- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NoteManager.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NoteManagerTest.java
When multi users perform some notebook/folder operation, like rename or move, some notebooks become not accessible from zeppelin page, while they are still existing on the HDFS, and only resort to restart Zeppelin daemon to solve the problem.
In this PR, unit test is created to simulate the concurrent request scenario and reproduce the issue successfully, including the operations of saveNote, moveNote, moveFolder and removeNote.
Accordingly, some changes are made to ensure thread safety of note manager operation, so that the note or folder info will not be lost, after which the unit test should get passed.
Bug Fix
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5744
* Automated unit tests for the change is added.
* Is …
> [ZEPPELIN-5744] Allow NoteManager for concurrent operation

- markdown/src/main/java/org/apache/zeppelin/markdown/FlexmarkParser.java
- markdown/src/test/java/org/apache/zeppelin/markdown/FlexmarkParserTest.java
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java
This is implemented by flexmark. A new configuration is also added, and
this configuration is turned on by default.
Zeppelin should support escaping html in markdown.
* Bug Fix
* [ZEPPELIN-5746](https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-5746)
* CI
I also noticed there is another call of flexmark in `org.apache.zeppelin.jupyter.parser.MarkdownParser`. But it seems the package `jupyter` can not read from configuration. I am not sure if this occurrence should be fixed or not. Feel free to tell me if this need to be fixed. :)
> ZEPPELIN-5746: Add support for escaping html in markdown

- pom.xml
- zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java
- zeppelin-web/src/WEB-INF/web.xml
* Upgrade jetty version to 9.4.43.v20210629
* Change servlet settings to support jetty 9.4.43.v20210629
* Bug Fix
* None
* https://issues.apache.org/jira/browse/ZEPPELIN-5434
* Locally tested, CI 
> [ZEPPELIN-5434] Upgrade jetty version to 9.4.43.v20210629

- zeppelin-server/src/main/java/org/apache/zeppelin/rest/InterpreterRestApi.java
This small change logs the user, which restarts Zeppelin Interpreter.
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5759
> [ZEPPELIN-5759] Add user to restartSetting

- zeppelin-interpreter/src/main/java/org/apache/zeppelin/util/ExecutorUtil.java
- zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java
- zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterEventTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/service/NotebookServiceTest.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/CronJob.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/MetricCronJobListener.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/NoSchedulerService.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/QuartzSchedulerService.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/SchedulerService.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/ZeppelinCronJobTriggerListerner.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/search/LuceneSearch.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
This pull request introduces a mechanism to initialize Notes in the background.
A consumer is passed, which is then called with the NoteId.
The consumer itself is responsible for checking, for example, whether the note still exists.
The initialization runs in several threads. The consumer must therefore be thread-safe.
This approach scales well, in my opinion, because it makes effective use of NoteCache. Another approach, e.g. to initialize the Notes in the sub-module, would not utilize the NoteCache as effectively. This is true if one sub-module is faster than the other.
Changes to the CronJob behavior:
As soon as a CronJob is executed, we have checked in the execution whether it is allowed to execute the Notes at all. If not, we have skipped it. With the changes in this PR we check …
> [ZEPPELIN-5754] Init Notes in background

- .github/workflows/quick.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> [MINOR] Set permissions for GitHub actions

- docs/setup/storage/storage.md
- zeppelin-plugins/notebookrepo/s3/pom.xml
- zeppelin-plugins/notebookrepo/s3/src/test/java/org/apache/zeppelin/notebook/repo/S3NotebookRepoTest.java
Currently NotebookRepo S3 is not able to assume role from env variables due to missing aws sts sdk
- added missing dependency
- fixed documentation
Bug Fix
Improvement
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5757
* Does this needs documentation? just minor fix, docs updated with this pull request
> [ZEPPELIN-5757] Assume role in NotebookRepo S3

- .github/workflows/core.yml
- pom.xml
- spark/interpreter/pom.xml
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/IPySparkInterpreter.java
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/PySparkInterpreter.java
- spark/interpreter/src/main/resources/python/zeppelin_ipyspark.py
- spark/interpreter/src/main/resources/python/zeppelin_pyspark.py
- spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkSqlInterpreterTest.java
- spark/scala-2.13/pom.xml
- spark/spark-shims/src/main/java/org/apache/zeppelin/spark/SparkVersion.java
- testing/env_python_3.7_with_R.yml
- testing/env_python_3.8_with_R.yml
- testing/env_python_3_with_R.yml
- testing/env_python_3_with_R_and_tensorflow.yml
- zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/SparkIntegrationTest33.java
- zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/ZeppelinSparkClusterTest33.java
Trivial PR to support spark 3.3
* Add profile spark-3.3
* Add integration tests for spark-3.3
* Due to api change, sqlContext in pyspark is set via different api in spark 3.3
Feature
* https://issues.apache.org/jira/startup.jsp?returnTo=%2Fbrowse%2FZEPPELIN-5755
* 
* CI pass
> [ZEPPELIN-5755] Support Spark 3.3

- .github/workflows/core.yml
- zeppelin-server/pom.xml
When building from the source code, the default profile activation option of the zeppelin-server module is "using-source-tree", so I got the error as in the screenshot. So I modified activeByDefault value of hadoop3 profile in the "zeppelin-server module" to true for successful build.
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5762
I tested with Travis CI, which is set by default. And after modifying the source code, I tried to build again.
* ```./mvnw clean package -DskipTests ``` before modifying the profile with 'hadoop2'
* ```./mvnw clean package -DskipTests ``` after modifying the profile with 'hadoop2'
> [ZEPPELIN-5762] Modify activeByDefault value of hadoop3 profile to true for successful build.

- docs/development/contribution/how_to_contribute_code.md
- docs/development/writing_zeppelin_interpreter.md
- docs/interpreter/bigquery.md
- docs/interpreter/geode.md
- docs/interpreter/submarine.md
- docs/quickstart/spark_with_zeppelin.md
- docs/setup/deployment/cdh.md
- docs/setup/deployment/virtual_machine.md
- docs/usage/other_features/cron_scheduler.md
Most broken links have been updated with links from the latest documentation. However, in the case of cdh.md and cron_schduler.md, I modified it in a different way.
For cdh.md, the Cloudera official document disappeared. so i replaced it with a docker hub site with the same content. And  for cron_scheduler.md, I replaced it with the version 2.2.2 site to match version 2.2.x.
Bug Fix
Documentation
https://issues.apache.org/jira/browse/ZEPPELIN-5777
I tested it using [markdown-link-checker](https://github.com/tcort/markdown-link-check)
The test proceeded as follows.
```bash
npm install -g markdown-link-check
cd zeppelin/docs
find . -name \*.md -print0 | xargs -0 -n1 markdown-link-check > result.txt
cat result.txt | grep 404
```
* Does the licenses files need to update? no
* Is there …
> [ZEPPELIN-5777] Fix dead links in docs

- zeppelin-server/src/main/java/org/apache/zeppelin/rest/AbstractRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/ClusterRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/CredentialRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/InterpreterRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/LoginRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRepoRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/SecurityRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/SessionRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/CheckpointNoteRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/CredentialRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/CronRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/GetNoteByPathRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/InterpreterInstallationRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/LoggerRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/NewInterpreterSettingRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/NewNoteRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/NewParagraphRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/NoteJobStatus.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/NotebookRepoSettingsRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/ParagraphJobStatus.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/PermissionRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/RenameNoteRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/RestartInterpreterRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/UpdateInterpreterSettingRequest.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/UpdateParagraphRequest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterEventTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookRestApiTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/ZeppelinRestApiTest.java
This pull request adds the roles of a user to API request. See `zeppelin-server/src/main/java/org/apache/zeppelin/rest/AbstractRestApi.java`-
Various Rest-API classes now inherit from `AbstractRestApi.java` to avoid duplicate code. 
Added some request classes in preparation for a possible switch to JSON-B.
The deserialization of request to Java objects has been unified.
`zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/NotebookResponse.java` was removed because no usage was detected.
Bug Fix, Refactoring
* https://issues.apache.org/jira/browse/ZEPPELIN-5769
* CI
> [ZEPPELIN-5769] Roles in API-Request

- .gitattributes
The eof setting of gitattributes was applied to all files including `.js`, so there was a problem that the file was changed in the Windows environment.
So, I removed the space in the eof setting of gitattributes to apply only to `.js`.
Hot Fix
[ZEPPELIN-3945](https://issues.apache.org/jira/browse/ZEPPELIN-3945)
> [HOTFIX] [ZEPPELIN-3945] Remove blank in .gitattributes

- conf/zeppelin-site.xml.template
When trying to run Zeppelin on Windows WSL linux, server property in Zeppelin-site.xml should be set to 0.0.0.0.
But, we don't change from 127.0.0.0 to 0.0.0.0 because of security issue. I think that we should at least write a comment.
Documentation
https://issues.apache.org/jira/browse/ZEPPELIN-4794
CI
* Does the licenses files need to update? No.
> [ZEPPELIN-4794] Add comment about changing localhost when running Zeppelin on WSL or Windows

- scripts/docker/zeppelin/bin/Dockerfile
Fixes issues such as trying to add a new interpreter belonging to "jdbc" group having hive-jdbc conf results in missing dependencies (tools.jar) and such.
Bug Fix
(none)
https://issues.apache.org/jira/browse/ZEPPELIN-5789
Build, publish and run the image via Dockerfile `docker run -d -p 80:8080 --name test imagename`
* Does the licenses files need to update? NO
* Is there breaking changes for older versions? NO
> [ZEPPELIN-5789] Update Dockerfile to use JDK instead of JRE

- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/JobManager.java
zeppelin-interpreter-flink-yarn produce a lot of logs, caused disk space to run out
Improvement
I think negative value is invalid input, so I make it just return and not to add job
But, the issuer suggest that set default value 1000. Is it better?
* https://issues.apache.org/jira/browse/ZEPPELIN-5638
* CI
> [ZEPPELIN-5638] Add flink job interval check

- zeppelin-web/package-lock.json
- zeppelin-web/package.json
In the [ZEPPELIN-5786] Remove sap interpreter  pr, the rimraf version overrided from 3.0.2 to 2.5.4 unintentionally.
Therefore it needs to be fixed back to 3.0.2 version.
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5802
* CI
* Does the licenses files need to update? N
> [ZEPPELIN-5802][MINOR] fix rimraf version

- python/src/main/java/org/apache/zeppelin/python/IPythonInterpreter.java
- zeppelin-jupyter-interpreter/src/main/java/org/apache/zeppelin/jupyter/JupyterKernelInterpreter.java
- zeppelin-jupyter-interpreter/src/main/java/org/apache/zeppelin/jupyter/PythonPackagePredicate.java
This pull request changes the Python dependency check minimally to get high flexibility for the package check.
- Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5810
* CI
> [ZEPPELIN-5810] Allow both package names jupyter_client and jupyter-client

- jdbc/src/test/java/org/apache/zeppelin/jdbc/JDBCInterpreterTest.java
Now In test cases `JDBCInterpreterTest.testMultiTenant_1` and `JDBCInterpreterTest.testMultiTenant_1`, the jdbc interpreter would try to connect h2 databases with 3 non-existed user.  Although It does not affect the running of the entire test case, it has two consequences:
1. It would cost more time to execute these two test case. The execution time of every test case time would be reduced from over 1 second to 50 milliseconds if the users is exsited.
2. And also the interpreter would log a long message about `JdbcSQLInvalidAuthorizationSpecException` ,  which may mislead developer who is unfamiliar to JDBC module into thinking there is something wrong with the test case. I found  this problem when I develop for ticket [ZEPPELIN-5493](https://issues.apache.org/jira/browse/ZEPPELIN-5493) , …
> [ZEPPELIN-5816] [MINOR] [JDBC] JDBCInterpreterTest.testMultiTenant_* improvement

- zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/SparkIntegrationTest.java
Unfortunately, the main reason of the error could not be found.
I have cleared the GitHub CI cache, unfortunately the problem was still present.
Following comment is very helpful to further understand the artifact resolution. https://github.com/databricks/spark-redshift/issues/244#issuecomment-347082455
This PR is mainly a workaround, so there is no reference to the library jackson-annotations;2.6.0.
- Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5819
* CI
> [ZEPPELIN-5819] Update to newer geoip jar

- pom.xml
- zeppelin-distribution/src/bin_license/LICENSE
This PR is to upgrade version of commons-configuration from 2.7 to 2.8 due to [CVE-2022-33980](https://mvnrepository.com/artifact/org.apache.commons/commons-configuration2/2.7).
Bug Fix
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5800
* CI passed
> [ZEPPELIN-5800] upgrade version of apache commons configuration2 to 2.8

- .github/workflows/core.yml
- .github/workflows/frontend.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- zeppelin-plugins/launcher/k8s-standard/src/main/java/org/apache/zeppelin/interpreter/launcher/K8sRemoteInterpreterProcess.java
- zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/K8sRemoteInterpreterProcessTest.java
- zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/K8sStandardInterpreterLauncherTest.java
Some important spark configs can`t be passed via SparkConf in k8s and in client mode including spark.jars.packages and spark.driver.extraJavaOptions
This fix checks if these are set in interpreter configuration and passes them to spark-submit command 
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5760
updated test to test this fix
* Is there breaking changes for older versions?  No
> [ZEPPELIN-5760] fix passing configs to spark in k8s

- pom.xml
Update the protobuf plugin to a version that, among other things, no longer overwrites the protoc compiler executable each time the project is built, which is convenient on systems where it needs some post-processing (current NixOS).
Improvement
> Update protobuf-maven-plugin from 0.5.0 to 0.6.1

- testing/downloadLivy.sh
Fix the download script so it can correctly download with livy 0.6.0 and later
Bug Fix
The `livy-0-7-with-spark-2-2-0-under-python3` GitHub Actions workflow uses this script, so we should be able to see that this doesn't fail to download livy anymore.
> update livy archive name

- bigquery/pom.xml
- influxdb/pom.xml
- pom.xml
- shell/pom.xml
- zeppelin-distribution/src/bin_license/LICENSE
- zeppelin-distribution/src/bin_license/licenses/LICENSE-gson-2.8.9
- zeppelin-integration/pom.xml
Upgrade gson to 2.8.9 due to CVE-2022-25647
The version of gson  is 2.8.6 in parent POM. And the LICENESE should be updated too.
Improvement
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5829
CI passed
> Upgrade gson to 2.8.9 due to CVE-2022-25647

- _includes/themes/zeppelin/_navigation.html
- security.md
This PR adds a 'Security' page to the website explaining what security characteristics people can expect from Zeppelin, and how to report any security issues people might find.
Improvement
Documentation
[ZEPPELIN-5830](https://issues.apache.org/jira/browse/ZEPPELIN-5830)
I had trouble running jekyll on my machine, so I have not verified the link in the menu and the page itself look good when rendered yet.
* Does the licenses files need to update? no
> [ZEPPELIN-5830] Add Zeppelin Security page to the website

- docs/quickstart/kubernetes.md
- k8s/zeppelin-server.yaml
- There has never been any Docker image named `zeppelin-interpreter` or `zeppelin-server`.
- The latest version also should be 0.10.1
All the examples inside and outside Zeppelin website/docs point to simply using `zeppelin-server.yaml` for K8s cluster : 
```sh
curl -s -O https://raw.githubusercontent.com/apache/zeppelin/master/k8s/zeppelin-server.yaml
kubectl apply -f zeppelin-server.yaml
```
There are lots of issues on StackOverFlow and 1 on Jira that indicate the Docker images mentioned in this YAML simply don't exist on Docker Hub. 
Documentation
* Open an issue on Jira …
> [ZEPPELIN-5191] Fix the wrong Docker image name in zeppelin-server.yaml

- .github/workflows/core.yml
- dev/change_scala_version.sh
- docs/setup/basics/how_to_build.md
- docs/setup/deployment/flink_and_spark_cluster.md
- flink/flink-scala-parent/pom.xml
- jdbc/pom.xml
- livy/pom.xml
- pom.xml
- spark/interpreter/pom.xml
- zeppelin-display/pom.xml
This PR removes scala 2.10 because of missing support for JDK 11. It also changes the scala compile maven plugin to `net.alchim31.maven`.
- Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5836
* CI
> [ZEPPELIN-5836] Remove scala-2.10 because it has no JDK 11 Support

- docs/interpreter/hive.md
- docs/interpreter/jdbc.md
- jdbc/src/main/java/org/apache/zeppelin/jdbc/JDBCInterpreter.java
- jdbc/src/main/java/org/apache/zeppelin/jdbc/JDBCUserConfigurations.java
- jdbc/src/test/java/org/apache/zeppelin/jdbc/JDBCInterpreterTest.java
Currently, zeppelin allow user to run multiple kinds of sql in one interpreter, e.g.
```
%jdbc(db=mysql)
%jdbc(db=hive){code}
```
 
But this would make jdbc interpreter very complicated, and hard to maintain.
 
This PR is to proposal to remove this feature, so that user need to create separated interpreter for each database.
```
%mysql
%hive
```
Refactoring
* Open an issue on Jira [ZEPPELIN-5493](https://issues.apache.org/jira/browse/ZEPPELIN-5493)
CI passed
> [ZEPPELIN-5493] Remove prefix in jdbc interpreter

- docs/_includes/themes/zeppelin/_navigation.html
- docs/setup/operation/monitoring.md
- examples/dashboard.json
This PR adds an example grafana dashboard for zeppelin based on prometheus metrics
- Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5123
* Enable the Prometheus metrics endpoint in Zeppelin
* Let Prometheus monitor your Zeppelin instance
* Set up Grafana with Prometheus as data source
* Include the dashboard
* Does this needs documentation? Maybe
> [ZEPPELIN-5123] Add an example grafana dashboard

- pom.xml
- zeppelin-jupyter-interpreter/pom.xml
This PR changes the plugin to compile the proto files. The Eclipse IDE support is very good and it works immediately after integration.
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5832
* CI
> [ZEPPELIN-5832] Use protoc-jar-maven-plugin, which has a good IDE support

- spark/interpreter/pom.xml
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/AbstractSparkScalaInterpreter.java
- spark/spark2-shims/src/main/java/org/apache/zeppelin/spark/Spark2Shims.java
- spark/spark3-shims/src/main/java/org/apache/zeppelin/spark/Spark3Shims.java
Fix it by using `commons-lang3` instead of `commons-lang`
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5763
* Manually tested
> [ZEPPELIN-5763] NoClassDefFoundError in spark interpreter: org/apache/commons/lang/StringUtils

- pom.xml
Remove outdated maven plugin setting.
I saw some warnings when I check some maven logs.
```
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
```
I tried to find the package in maven central but couldn't find it and reached a description of …
> [MINOR] Remove warnning

- assets/themes/zeppelin/css/style.css
- security.md
When creating #4478 I ran into trouble running jekyll so I couldn't test the output.
I have since tested the output and made some updates accordingly. I have also pushed the generated site to https://github.com/raboof/zeppelin-docs.
Bug Fix
Documentation
[ZEPPELIN-5830](https://issues.apache.org/jira/browse/ZEPPELIN-5830)
Use jekyll 3.x to test the documentation generation.
* Does this needs documentation? N/A
> [ZEPPELIN-5830] Zeppelin Security page header styling

- flink/flink-scala-parent/pom.xml
- pom.xml
Remove the elicpse-related maven plugin which was retired 7 years ago.
Improvement
N/A
Already been tested by some contributors
> [MINOR] Remove `maven-eclipse-plugin`

- .asf.yaml
Enable auto link feature to connect with issues.a.o/ZEPPELIN.
Improvement
N/A
Ppl can click the issue number like ZEPPELIN-XXXX
> [MINOR] Add github autolink to ZEPPELIN

- .mvn/wrapper/maven-wrapper.properties
- pom.xml
- zeppelin-distribution/src/bin_license/LICENSE
Bump bouncycastle 1.70.
```
➜  apache-zeppelin git:(master) java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Zulu 8.62.0.19-CA-macos-aarch64) (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Zulu 8.62.0.19-CA-macos-aarch64) (build 25.332-b09, mixed mode)
```
The transitive dependencies can not be resolved correctly on my mac when using bouncycastle 1.60, and the build failed w/ same reason.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project zeppelin-zengine: Compilation failure: Compilation failure:
[ERROR] /Users/chengpan/Projects/apache-zeppelin/zeppelin-zengine/src/main/java/org/apache/zeppelin/user/Encryptor.java:[20,31] package org.bouncycastle.crypto does not exist
[ERROR] …
```
> [ZEPPELIN-5856] Bump bouncycastle 1.70

- docs/quickstart/docker.md
This PR adds a warning to the documentation for setting up Zeppelin Interpreter on Docker, warning that the docker daemon should not be exposed to untrusted users.
Improvement
Documentation
[ZEPPELIN-5863](https://issues.apache.org/jira/browse/ZEPPELIN-5863)
* Does this needs documentation? N/a
> [ZEPPELIN-5863] Warn not to expose the docker daemon to untrusted users

- jdbc/pom.xml
This PR proposes to exclude hbase-server from hive-jdbc, because hive-jdbc does not require that, and the transitive deps of hbase-server cause issue on resolving project in IDEA
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5867
Existing CI.
> [ZEPPELIN-5867][JDBC] Exclude hbase-server from hive-jdbc

- .github/workflows/core.yml
- .github/workflows/frontend.yml
- .github/workflows/quick.yml
Specify the condition to trigger GitHub action when pushing commits. E.g. dependabot's PRs run twice for GitHub action as we allow to run it for all branches in the repository.
Bug Fix
N/A
* Check dependabot's PR so that it runs only once for each Github actions
> [MINOR] Specify branch names for Github action

- pom.xml
- zeppelin-plugins/notebookrepo/s3/pom.xml
- zeppelin-zengine/pom.xml
Fixing build error when using aarch jdk for mac OS. our version of node doesn't support amd64 arch but the old plugin tries to download arm version.
Bug Fix
N/A
* Pass to build with arm jdk in macOS
* Is there breaking changes for older versions? No 
> [MINOR] Support aarch for frontend plugin

- .appveyor.yml
Disabling to execute AppVeyor jobs for branches for `dependabot`.
Improvement
* N/A
* Open `dependabot` issue
* @dependabot rebase
* Check only one appveyor job
> [MINOR] Disable depeanabot branches for AppVeyor

- .github/workflows/core.yml
- flink/flink-scala-parent/pom.xml
- python/src/test/java/org/apache/zeppelin/python/IPythonInterpreterTest.java
- spark/interpreter/pom.xml
- submarine/pom.xml
- zeppelin-interpreter-shaded/pom.xml
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/util/ProcessLauncher.java
- zeppelin-jupyter-interpreter/pom.xml
- zeppelin-zengine/pom.xml
This pull request includes several things:
- Changing the shading prefix so we don't have recursion. See [MSHADE-252](https://issues.apache.org/jira/browse/MSHADE-252?focusedCommentId=17314377&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17314377)
- Remove unnecessary Maven plugin executions.
- Using grpc-netty-shaded as described in the [official documentation](https://github.com/grpc/grpc-java#download).
- Refactoring
* via CI
> [ZEPPELIN-5861] Correct shading Prefix

- docs/quickstart/docker.md
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java
- zeppelin-plugins/launcher/docker/pom.xml
- zeppelin-plugins/launcher/docker/src/main/java/org/apache/zeppelin/interpreter/launcher/DockerInterpreterProcess.java
- zeppelin-plugins/launcher/docker/src/main/java/org/apache/zeppelin/interpreter/launcher/utils/TarUtils.java
- zeppelin-plugins/launcher/docker/src/test/java/org/apache/zeppelin/interpreter/launcher/DockerInterpreterProcessTest.java
[Powermock](https://github.com/powermock/powermock/issues/929) is not supported in JUnit5. We should not be dependent on Powermock. This PR removes the Powermock dependency from the Docker plugin. It also makes some refactoring.
Instead of using environment variables directly, this possibility of configuration is moved to ZeppelinConfiguration. In order not to break the naming scheme in ZeppelinConfiguration, the environment variables that were previously accessed must be changed.
`CONTAINER_SPARK_HOME` -> `ZEPPELIN_DOCKER_CONTAINER_SPARK_HOME`
`UPLOAD_LOCAL_LIB_TO_CONTAINTER` -> `ZEPPELIN_DOCKER_UPLOAD_LOCAL_LIB_TO_CONTAINTER`
`DOCKER_HOST` -> `ZEPPELIN_DOCKER_HOST`
`DOCKER_TIME_ZONE` -> `ZEPPELIN_DOCKER_TIME_ZONE`
Except for DOCKER_TIME_ZONE, I have not found any references in the …
> [ZEPPELIN-5855] Refactor docker plugin and remove powermock

- testing/env_python_3.8_with_R.yml
Recently CI is failed due to sqlalchemy api change. This PR enforce the sqlalchemy version to make the CI pass.
Hot Fix
* CI pass
> [HOTFIX] Fix CI failure due to sqlalchemy api change

- flink/pom.xml
A trivial PR to use flink-113 as default profile, so that user don't need to specify profile to build flink-interpreter modules. Otherwise the following command won't build flink-interpreter module.
```
mvn clean package -DskipTests
```
Hot Fix
* Manually tested
> [MINOR] Use flink-113 as default profile

- zeppelin-server/pom.xml
Fixed maven build failed on module `zeppelin-server` with profile `hadoop3`.
Bug Fix
* ZEPPELIN-5881
* Try to build module zeppelin-server by command
`./mvnw -B -pl 'zeppelin-server,zeppelin-zengine,zeppelin-common,zeppelin-interpreter,zeppelin-jupyter' clean package -DskipTests -Pbuild-distr -Pinclude-hadoop -Phadoop3 -Pweb-angular`
> [ZEPPELIN-5881] Missing dependency when package zeppelin-server module

- pom.xml
- zeppelin-plugins/launcher/cluster/src/test/java/org/apache/zeppelin/interpreter/launcher/ClusterInterpreterLauncherTest.java
- zeppelin-plugins/launcher/cluster/src/test/java/org/apache/zeppelin/interpreter/launcher/ClusterMockTest.java
- zeppelin-plugins/launcher/k8s-standard/pom.xml
- zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/K8sRemoteInterpreterProcessTest.java
- zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/K8sSpecTemplateTest.java
- zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/K8sStandardInterpreterLauncherTest.java
- zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/K8sUtilsTest.java
- zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/PodPhaseWatcherTest.java
- zeppelin-plugins/notebookrepo/filesystem/src/test/java/org/apache/zeppelin/notebook/repo/FileSystemNotebookRepoTest.java
- zeppelin-plugins/notebookrepo/gcs/pom.xml
- zeppelin-plugins/notebookrepo/gcs/src/test/java/org/apache/zeppelin/notebook/repo/GCSNotebookRepoTest.java
- zeppelin-plugins/notebookrepo/github/src/test/java/org/apache/zeppelin/notebook/repo/GitHubNotebookRepoTest.java
- zeppelin-plugins/notebookrepo/mongo/pom.xml
- zeppelin-plugins/notebookrepo/mongo/src/test/java/org/apache/zeppelin/notebook/repo/MongoNotebookRepoTest.java
- zeppelin-plugins/notebookrepo/mongo/src/test/java/org/apache/zeppelin/notebook/repo/ToPathArrayTest.java
- zeppelin-plugins/notebookrepo/oss/src/test/java/org/apache/zeppelin/notebook/repo/OSSNotebookRepoTest.java
- zeppelin-plugins/notebookrepo/s3/pom.xml
- zeppelin-plugins/notebookrepo/s3/src/test/java/org/apache/zeppelin/notebook/repo/S3NotebookRepoTest.java
- zeppelin-plugins/pom.xml
This pull request migrates the JUnit 4 tests to Junit 5 tests.
Refactoring
https://issues.apache.org/jira/browse/ZEPPELIN-5879
* CI
> [ZEPPELIN-5879] Migrate Zeppelin Plugins to JUnit5

- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/AuthorizationService.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NotebookAuthorizationInfoSaving.java
This pull request migrates solve the concurrency problem caused by multiple concurrent calls to note clone.
[Bug Fix]
- [[ZEPPELIN-5885](https://issues.apache.org/jira/browse/ZEPPELIN-5885)]
- Try to build module zeppelin-zengine by command
./mvnw -B -pl 'zeppelin-server,zeppelin-zengine,zeppelin-common,zeppelin-interpreter,zeppelin-jupyter' clean package - 
DskipTests -Pbuild-distr -Pinclude-hadoop -Phadoop3 -Pweb-angular
> [ZEPPELIN-5885] Solve the concurrency clone note

- zeppelin-interpreter/src/main/java/org/apache/zeppelin/scheduler/AbstractScheduler.java
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/scheduler/Job.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreter.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/RemoteScheduler.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/scheduler/RemoteSchedulerTest.java
This PR changes the RemoteScheduler
The main change is the executor of the RemoteScheduler. It's now a separate FIFO Executor (one Thread). As a result, jobs are now queued in the Zeppelin server and not in the RemoteInterpreter.
Since previously the jobs were queued in the remote interpreter due to parallelism in the Zeppelin server, the cancellation of jobs did not work, which is why the test failed.
The interrupt behaviour has also been improved.
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5900
* CI
> [ZEPPELIN-5900] Fix RemoteSchedulerTest

- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NoteManager.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NoteManagerTest.java
This pull request adds a cache cleanup method that attempts to remove an item from the cache that is not the eldest item and also does not have a read flag.
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5903
* CI
> [ZEPPELIN-5903] Improve LRU NoteCache - Add a cleanup

- zeppelin-client/src/main/java/org/apache/zeppelin/client/ParagraphResult.java
use ZeppelinClient  Example:
```
public class ZeppelinTest {
public static void main(String[] args) throws Exception {
ClientConfig clientConfig = new ClientConfig("http://ip:8080");
ZeppelinClient zClient = new ZeppelinClient(clientConfig);
String zeppelinVersion = zClient.getVersion();
System.out.println("Zeppelin version: " + zeppelinVersion);
// execute note 2A94M5J1Z paragraph by paragraph
try {
//ParagraphResult paragraphResult = zClient.executeParagraph("2HXQ8YRYN", "20230330-101251_25695257");
ParagraphResult paragraphResult = zClient.executeParagraph("2HXQ8YRYN","20230330-101251_25695257");
System.out.println("Execute the 1st spark tutorial paragraph, paragraph result: " + paragraphResult);
System.out.println("Execute the 4th spark tutorial paragraph, paragraph result: " + …
```
> [ZEPPELIN-5893] NPE in ParagraphResult when getting progress from paragraphJson

- elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/client/ElasticsearchClientTypeBuilderTest.java
- markdown/src/test/java/org/apache/zeppelin/markdown/FlexmarkParserTest.java
- zeppelin-distribution/src/bin_license/LICENSE
- zeppelin-interpreter/pom.xml
- zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterEventTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/recovery/RecoveryTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/CredentialsRestApiTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/HeliumRestApiTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookRepoRestApiTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookRestApiTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookSecurityRestApiTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/ZeppelinRestApiTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/server/HtmlAddonResourceTest.java
This PR is minimally invasive. This PR updates atomix from 3.0.0-rc4 to 3.0.0-rc5 which removes hamcrest-all as compile dependency from zeppelin-interpreter.
Deprecated methods were migrated accordingly.
https://github.com/atomix/atomix-archive/compare/atomix-3.0.0-rc4...atomix-3.0.0-rc5
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5910
* CI
* Does the license files need to update? Yes
> [ZEPPELIN-5910] Remove hamcrest-all as compile dependency

- zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/launcher/InterpreterLauncher.java
- zeppelin-plugins/launcher/cluster/src/main/java/org/apache/zeppelin/interpreter/launcher/ClusterInterpreterLauncher.java
- zeppelin-plugins/launcher/docker/src/main/java/org/apache/zeppelin/interpreter/launcher/DockerInterpreterLauncher.java
- zeppelin-plugins/launcher/flink/src/main/java/org/apache/zeppelin/interpreter/launcher/FlinkInterpreterLauncher.java
- zeppelin-plugins/launcher/k8s-standard/src/main/java/org/apache/zeppelin/interpreter/launcher/K8sStandardInterpreterLauncher.java
- zeppelin-plugins/launcher/yarn/src/main/java/org/apache/zeppelin/interpreter/launcher/YarnInterpreterLauncher.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncher.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/launcher/StandardInterpreterLauncher.java
This PR removes the double holding of properties.
The main problem: The InterpreterLauncher class  is a singleton, because of your PluginManager Cache Implementation.
https://github.com/apache/zeppelin/blob/22ae6cdcd1f526b66808c2b994b53f808f390cfe/zeppelin-zengine/src/main/java/org/apache/zeppelin/plugin/PluginManager.java#L104C23-L126
As a result, every InterpreterProcess started by an InterpreterLauncher has the same properties, because we have the following lines of code in almost all launchers.
https://github.com/apache/zeppelin/blob/22ae6cdcd1f526b66808c2b994b53f808f390cfe/zeppelin-plugins/launcher/yarn/src/main/java/org/apache/zeppelin/interpreter/launcher/YarnInterpreterLauncher.java#L44
https://github.com/apache/zeppelin/blob/22ae6cdcd1f526b66808c2b994b53f808f390cfe/zeppelin-plugin …
> [ZEPPELIN-5897] Remove launcher properties and only use the current context properties

- flink/flink-scala-2.11/src/main/scala/org/apache/zeppelin/flink/FlinkScala211Interpreter.scala
- flink/flink-scala-2.12/src/main/scala/org/apache/zeppelin/flink/FlinkScala212Interpreter.scala
- flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/FlinkInterpreter.java
- flink/flink-scala-parent/src/main/scala/org/apache/zeppelin/flink/FlinkScalaInterpreter.scala
JDK 11 is more strict about creation by reflection.
At this point we have only a Classloader and no URLClassloader.
https://github.com/apache/zeppelin/blob/3fd026616efb6c7257b4eed09581d16ca7f71f78/flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/FlinkInterpreter.java#L86-L96
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5918
* CI
> [ZEPPELIN-5918] Use Classloader class for flink creation

- zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/ZSessionIntegrationTest.java
Spark 2.4 does not support JDK 11, so we should test with a newer Spark version here.
Refactoring
* https://issues.apache.org/jira/browse/ZEPPELIN-5917
* CI
> [ZEPPELIN-5917] Integration tests with newer spark version

- spark/pom.xml
This PR removes an unnecessary executions of the Scala Maven plugin in the `spark-parent` pom project.
The `spark-scala-parent` project configures the Scala Maven plugin for the Spark Scala submodules. 
Unnecessary executions:
```
2023-05-26T11:41:01.8159846Z [INFO] --- scala-maven-plugin:4.6.3:add-source (eclipse-add-source) @ spark-parent ---
2023-05-26T11:41:01.8172148Z [INFO] Add Source directory: /home/runner/work/zeppelin/zeppelin/spark/src/main/scala
2023-05-26T11:41:01.8180408Z [INFO] Add Test Source directory: /home/runner/work/zeppelin/zeppelin/spark/src/test/scala
2023-05-26T11:41:01.8184308Z [INFO] 
2023-05-26T11:41:01.8196734Z [INFO] --- maven-remote-resources-plugin:1.7.0:process (process-resource-bundles) @ spark-parent ---
2023-05-26T11:41:01.8216849Z [INFO] Preparing …
```
> [ZEPPELIN-5919] Compile scala only where scala code is present

- python/src/main/resources/python/zeppelin_context.py
- python/src/test/java/org/apache/zeppelin/python/BasePythonInterpreterTest.java
If z.show is used with a Panda DataFrame that has a timestamp as index, then a DeprecationWarning appears for every row in the data frame.
This issue was fixed.
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5920
* A new unit test was added
> [ZEPPELIN-5920] Fix deprecation warnings

- scalding/pom.xml
Fix broken url of conjars repository.
The old link: https://conjars.org/repo is deprecated, changed to https://conjars.wensel.net/repo
Bug Fix
* CI
> fix conjars repository url

- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/AuthorizationService.java
This pull request migrates solve the concurrency calls to `saveNoteAuth`.
[Bug Fix]
[ZEPPELIN-5927](https://issues.apache.org/jira/browse/ZEPPELIN-5927)
Try to build module zeppelin-zengine by command
./mvnw -B -pl 'zeppelin-server,zeppelin-zengine,zeppelin-common,zeppelin-interpreter,zeppelin-jupyter' clean package -
DskipTests -Pbuild-distr -Pinclude-hadoop -Phadoop3 -Pweb-angular
> [ZEPPELIN-5927]Solve the concurrency calls to `saveNoteAuth`.

- zeppelin-server/src/main/java/org/apache/zeppelin/socket/ConnectionManager.java
- zeppelin-server/src/test/java/org/apache/zeppelin/socket/ConnectionManagerTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/socket/NotebookServerTest.java
This PR deletes a map element if the collection behind the map key is empty, so that the map size can decrease.
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5926
* CI
> [ZEPPELIN-5926] Remove map entries if Collection is empty

- zeppelin-plugins/launcher/k8s-standard/pom.xml
- zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/PodPhaseWatcherTest.java
This PR re-enables the unit tests in K8's launcher.
- Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5403
* CI, with several runs
> [ZEPPELIN-5403] Update kubernetes client to 5.4.1 and fix unit tests

- jdbc/pom.xml
Bump h2 version for fixing CVE-2022-23221
Improvement
https://issues.apache.org/jira/browse/ZEPPELIN-5932
> [ZEPPELIN-5932] Upgraded h2 version in jdbc

- .asf.yaml
Changing Github's notification email addresses in order to use `reviews@zeppelin.apache.org`
Improvement
N/A
> [MINOR] Change notification emails

- pom.xml
This PullRequest updates the used Jetty version to the currently latest 9.4.x version.
Please note that Jetty 9.4.x is end of life. https://github.com/eclipse/jetty.project/issues/7958
For Jetty 10 or 11 at least JDK 11 is required.
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5936
* CI
> [ZEPPELIN-5936] Update jetty to latest 9.x version

- pom.xml
- rlang/src/main/java/org/apache/zeppelin/r/ZeppelinRDisplay.java
- zeppelin-distribution/src/bin_license/LICENSE
Bump jsoup version for fixing CVE-2021-37714
Improvement
https://issues.apache.org/jira/browse/ZEPPELIN-5935
> [ZEPPELIN-5935] Update jsoup version

- zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
- zeppelin-server/src/test/java/org/apache/zeppelin/service/NotebookServiceTest.java
Checking invalid note name like './';
Hot Fix
* N/A
* Invalid note name should be rejected
* N/A
> [HOTFIX] Validate note name

- testing/env_python_3.7_with_R.yml
- testing/env_python_3.8_with_R.yml
- testing/env_python_3_with_R.yml
- testing/env_python_3_with_R_and_tensorflow.yml
- testing/env_python_3_with_flink_112.yml
- testing/env_python_3_with_flink_113.yml
- testing/env_python_3_with_flink_114.yml
- testing/env_python_3_with_flink_115.yml
- testing/env_python_3_with_flink_116.yml
Install holoview 1.16, 1.17 drops python 3.7 support see https://github.com/holoviz/holoviews/pull/5695
Hot Fix
* CI
> [Ci-Hotfix] Install holoview 1.16, 1.17 drops python 3.7 support

- .github/workflows/core.yml
This PR results in Checkstyle being run in the default build.
Background is my comment https://github.com/apache/zeppelin/pull/4620#issuecomment-1596241260
- Improvement
* CI
> [Minor] Execute checkstyle during default build

- docs/interpreter/jdbc.md
- update maven url to download redshift jdbc dependencies on migrated repo
Documentation
[as-is]
```
java.lang.ClassNotFoundException: com.amazon.redshift.jdbc42.Driver
```
- update docs to download redshift jdbc driver package from migrated repository
- maven: https://mvnrepository.com/artifact/com.amazon.redshift/redshift-jdbc42
- git: https://github.com/aws/amazon-redshift-jdbc-driver
> docs: update maven url to download redshift jdbc dependencies on migrated repo

- elasticsearch/pom.xml
- elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/ElasticsearchInterpreterTest.java
- elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/client/ElasticsearchClientTypeBuilderTest.java
- elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/client/ElasticsearchClientTypeTest.java
Part of https://github.com/apache/zeppelin/pull/4641 
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5954
* CI
> [ZEPPELIN-5954] migrate elasticsearch to Junit5

- sparql/src/test/java/org/apache/zeppelin/sparql/SparqlJenaEngineTest.java
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5950
* CI
> [ZEPPELIN-5950] Migrate sparql to Junit5

- livy/src/main/java/org/apache/zeppelin/livy/BaseLivyInterpreter.java
- livy/src/test/java/org/apache/zeppelin/livy/LivyInterpreterIT.java
LivyInterpreter support more parameter when create session
Improvement
* https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-5962
> [ZEPPELIN-5962] LivyInterpreter support more parameter when create session

- zeppelin-zengine/pom.xml
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NoteManager.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
If a note is renamed by changing only the capitalization, the note is copied at the file system level when it is executed again.
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5964
* New unit test were added
> [ZEPPELIN-5964] Fix renaming bug

- dev/change_scala_version.sh
- docs/setup/basics/how_to_build.md
- k8s/zeppelin-server.yaml
- livy/pom.xml
- pom.xml
- rlang/pom.xml
- spark/README.md
- spark/interpreter/pom.xml
- spark/pom.xml
- spark/scala-2.12/pom.xml
- spark/scala-2.13/pom.xml
- spark/scala-2.13/src/main/scala/org/apache/zeppelin/spark/SparkScala213Interpreter.scala
- spark/spark3-shims/pom.xml
- zeppelin-integration/pom.xml
- zeppelin-web/pom.xml
Followup ZEPPELIN-5946, Use Spark 3.4.1 in default
Improvement
Documentation
ZEPPELIN-5946
Pass GA
> [ZEPPELIN-5946][FOLLOWUP] Use Spark 3.4.1 in default

- python/src/main/java/org/apache/zeppelin/python/IPythonInterpreter.java
- python/src/main/java/org/apache/zeppelin/python/PythonInterpreter.java
- python/src/main/java/org/apache/zeppelin/python/PythonUtils.java
- rlang/src/main/java/org/apache/zeppelin/r/IRInterpreter.java
- rlang/src/main/java/org/apache/zeppelin/r/RInterpreter.java
- rlang/src/main/java/org/apache/zeppelin/r/SparkRBackend.java
- rlang/src/main/java/org/apache/zeppelin/r/ZeppelinR.java
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/IPySparkInterpreter.java
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/PySparkInterpreter.java
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/SparkIRInterpreter.java
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/SparkInterpreter.java
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/SparkRInterpreter.java
- spark/interpreter/src/main/java/org/apache/zeppelin/spark/Utils.java
- spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkShimsTest.java
- spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkVersionTest.java
- spark/spark-shims/src/main/java/org/apache/zeppelin/spark/SparkShims.java
- spark/spark-shims/src/main/java/org/apache/zeppelin/spark/SparkVersion.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncher.java
Clean up unreachable code for legacy Spark 1.x and 2.x versions, since Zeppelin only supports Spark 3.2 ~ 3.4 now.
Improvement
ZEPPELIN-5946
Pass CI
> [ZEPPELIN-5946][FOLLOWUP] Clean up code for legacy Spark versions

- pom.xml
Jetty 9.x is EOL but still gets Security / Vulnerability triggered releases
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.52.v20230823
Improvement
ZEPPELIN-5968
Pass GA.
> [ZEPPELIN-5968] Bump Jetty 9.4.52.v20230823

- .github/workflows/core.yml
- docs/setup/basics/how_to_build.md
- spark/interpreter/pom.xml
- spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkInterpreterTest.java
- spark/spark-shims/src/main/java/org/apache/zeppelin/spark/SparkVersion.java
Spark 3.5.0 was released a few weeks ago, this PR tries to add Spark 3.5 support in Zeppelin.
https://spark.apache.org/releases/spark-release-3-5-0.html
Improvement
ZEPPELIN-5966
Update GitHub workflow to cover Spark 3.5 tests
* Does this needs documentation? Yes, updated correspondingly.
> [ZEPPELIN-5966] Support Spark 3.5

- python/src/main/resources/python/zeppelin_context.py
- python/src/test/java/org/apache/zeppelin/python/BasePythonInterpreterTest.java
z.show works with subtypes of DataFrames in python interpreter
Improvement
[ZEPPELIN-5975]
* Unit test
No
No
No
> [ZEPPELIN-5875] z.show works with subtypes of DataFrame

- .github/workflows/core.yml
- .github/workflows/frontend.yml
- docs/interpreter/python.md
- docs/interpreter/r.md
- testing/env_python_3.9_with_R.yml
- testing/env_python_3.yml
- testing/env_python_3_with_R.yml
- testing/env_python_3_with_flink_117.yml
Currently, Zeppelin only tests with Python 3.7(default) and 3.8.
According to https://endoflife.date/, Python 3.7 is EOL. This PR adds the Python 3.9 test with minimal tunes. Although Python 3.12 is available, I conservatively just moved to Python 3.9 for safety (I'm not a Python expert), also Python 3.9 is the first version officially supporting Apple Sillicon.
Improvement
ZEPPELIN-5979
Pass GA.
> [ZEPPELIN-5979] Support and use Python 3.9 in default

- zeppelin-plugins/notebookrepo/gcs/src/main/java/org/apache/zeppelin/notebook/repo/GCSNotebookRepo.java
- zeppelin-plugins/notebookrepo/gcs/src/test/java/org/apache/zeppelin/notebook/repo/GCSNotebookRepoTest.java
The main problem is the lack of credentials during the tests. I think it makes sense to skip the credential check and run the tests.
- Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5993
* CI
> [ZEPPELIN-5993] Fix GCSNotebookRepoTests

- conf/zeppelin-site.xml.template
- docs/development/helium/overview.md
Changing the default link for helium.json from s3 to zeppelin.apache.org
Hot Fix
* Is there breaking changes for older versions? Yes
* Does this needs documentation? Yes but already did it.
> [HOTFIX] Change the link of `helium.json` from S3 to zeppelin.apache.org

- zeppelin-server/src/main/java/org/apache/zeppelin/realm/LdapRealm.java
- zeppelin-server/src/test/java/org/apache/zeppelin/realm/LdapRealmTest.java
Escaping Ldap filters to mitigate un-intended behaviors
Hot Fix
N/A
* CI should be green
> [HOTFIX] Escape Ldap search filters

- zeppelin-web-angular/src/app/visualizations/table/table-visualization.component.html
…sively wide column widths resulted in the remaining fields being squeezed out of the screen, and nz table did not have a scroll bar set to display scrolling.
When I am using the new Zeppelin interface for querying with jdbc or Spark SQL, the resulting table cannot display all the content.
Example: If there is a MySQL table as follows.
When using zeppelin jdbc queries, the following results will be obtained:
You can see that only two fields are displayed.
The specific reason is that the use of excessively wide column widths resulted in the remaining fields being squeezed out of the screen, and nz table did …
> [NO-ISSUE] Reduce the minimum column width in table view

- zeppelin-interpreter/src/main/java/org/apache/zeppelin/helium/HeliumPackage.java
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/helium/SpellPackageInfo.java
- zeppelin-interpreter/src/test/java/org/apache/zeppelin/helium/ApplicationLoaderTest.java
- zeppelin-interpreter/src/test/java/org/apache/zeppelin/helium/HeliumPackageTest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/HeliumRestApiTest.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/helium/HeliumApplicationFactoryTest.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/helium/HeliumBundleFactoryTest.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/helium/HeliumLocalRegistryTest.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/helium/HeliumTest.java
Escaping HeliumPackage information when loading it.
Hot Fix
* N/A
* Malicious configuration will be parsed properly
> [HOTFIX] Escape HeliumPackage information

- flink/flink-scala-2.12/pom.xml
- pom.xml
- rlang/pom.xml
- shell/pom.xml
- submarine/pom.xml
- zeppelin-distribution/src/bin_license/LICENSE
- zeppelin-examples/zeppelin-example-clock/pom.xml
- zeppelin-examples/zeppelin-example-horizontalbar/pom.xml
- zeppelin-examples/zeppelin-example-spell-echo/pom.xml
- zeppelin-examples/zeppelin-example-spell-flowchart/pom.xml
- zeppelin-examples/zeppelin-example-spell-markdown/pom.xml
- zeppelin-examples/zeppelin-example-spell-translator/pom.xml
- zeppelin-interpreter-parent/pom.xml
- zeppelin-interpreter-shaded/pom.xml
- zeppelin-interpreter/pom.xml
- zeppelin-jupyter-interpreter-shaded/pom.xml
- zeppelin-plugins/notebookrepo/filesystem/pom.xml
- zeppelin-server/pom.xml
- zeppelin-zengine/pom.xml
* reload4j does not prevent us moving to log4jv2 later
* reload4j fixes some security issues in log4j
* it doesn't feel great for an ASF project to still be using insecure logging frameworks like log4j v1
Bug Fix
Improvement
Feature
Documentation
Hot Fix
Refactoring
> [NO-ISSUE] Use reload4j instead of log4j

- elasticsearch/pom.xml
- flink/flink-scala-2.12/pom.xml
- influxdb/pom.xml
- pom.xml
- zeppelin-distribution/src/bin_license/LICENSE
- zeppelin-plugins/notebookrepo/gcs/pom.xml
See ZEPPELIN-5996
Bug Fix
* [ZEPPELIN-5996](https://issues.apache.org/jira/browse/ZEPPELIN-5996)
> [NO-ISSUE] Upgrade org.json jar

- scripts/docker/zeppelin-interpreter/Dockerfile
- scripts/docker/zeppelin-server/Dockerfile
Fixed some errors while building k8s images.
zeppelin-interpreter Dockerfile:
fixed JAVA_HOME env
zeppelin-server Dockerfile:
Error "bzip2: Compressed file ends unexpectedly;" fixed by adding ---no-iri flag to wget
changed ARG version in both Dockerfiles
Bug Fix
> [ZEPPELIN-6001] k8s images fix

- jdbc/src/main/java/org/apache/zeppelin/jdbc/JDBCInterpreter.java
Currently we can monitor running SQL in JDBCInterpreter  but unable to know who/which note fire the SQL, especially a couple of users using zeppelin at the same time. 
Bond the SQL with additional info,  we can inform the user with user/noteid/paragragh info  if needed
Improvement
https://issues.apache.org/jira/browse/ZEPPELIN-6003
> [ZEPPELIN-6003] Log source info of SQL in JDBCInterpreter

- jdbc/src/main/java/org/apache/zeppelin/jdbc/SqlCompleter.java
NPE occur when adding the driver specific SQL completions. Some driver(hive-jdbc-uber-2.6.5.0-292.jar in my case) does not implement method `DatabaseMetaData.getDriverName()` well and cause exception , then fail to initialize `keywordCompleter`.
Since it is optional, we should avoid such driver interfere  the default one, and log it for the profession
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-6002
> [ZEPPELIN-6002] Fix completer NPE

- dev/common_release.sh
When untar the 0.11.1 RC1 tgz on Linux, I found the following warnings. It's actually caused by macOS `tar`'s default behavior, see more details at [SPARK-43395](https://issues.apache.org/jira/browse/SPARK-43395)
```
➜  zeppelin-0.11.1-rc1 tar -xzf zeppelin-0.11.1-bin-all.tgz
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
``` …
> [ZEPPELIN-6007] Enhance release scripts for tar shasum commands detection

- zeppelin-interpreter/src/test/java/org/apache/zeppelin/helium/HeliumPackageTest.java
- zeppelin-web/src/app/helium/helium.controller.js
Removing wrong logic for rendering helium description in helium
Hot Fix
N/A
JS in a helium description shouldn't be executed.
> [HOTFIX] Remove rendering helium description as HTML in Frontend

- scripts/docker/zeppelin/bin/Dockerfile
To update `zeppelin/scripts/docker/zeppelin/bin/Dockerfile` to OpenJDK 11
Follow up PR from https://github.com/apache/zeppelin/pull/4751 and https://github.com/apache/zeppelin/pull/4752
Bug Fix
* [ZEPPELIN-6011](https://issues.apache.org/jira/browse/ZEPPELIN-6011)
* Not too sure how to automate this testing as i'm new at this.
> update scripts/docker/zeppelin/bin/Dockerfile to JDK11

- bin/common.cmd
- bin/common.sh
#4146 delete the definition check about ZEPPELIN_IDENT_STRING in case of surefire version upgrade 
but it will make the log file names become: 
```
zeppelin--SERVER.log
zeppelin--SERVER.out
zeppelin-interpreter-jdbc-shared_process–SERVER.log
```
in the defintion of:
```
zeppelin-${ZEPPELIN_IDENT_STRING}-${HOSTNAME}.log
zeppelin-${ZEPPELIN_IDENT_STRING}-${HOSTNAME}.out
zeppelin-interpreter-%INTERPRETER_ID%%ZEPPELIN_IDENT_STRING%%HOSTNAME%.log
```
so, we revert changes about ZEPPELIN_IDENT_STRING to fix the filename
Hot Fix
https://issues.apache.org/jira/browse/ZEPPELIN-6017
> [ZEPPELIN-6017] Revert changes about ZEPPELIN_IDENT_STRING in ZEPPELIN-5421

- zeppelin-zengine/src/main/java/org/apache/zeppelin/user/Credentials.java
This PR skip credentials.json decryption if the file is empty. 
This allow using of type=bind on conf/credentials.json when running docker image especially for initial startup where credentials.json does not exist
Improvement
(https://issues.apache.org/jira/browse/ZEPPELIN-6022)
* CI with automated test
* Does this needs documentation? Maybe
> [ZEPPELIN-6022] Skip decryption of credentials.json when file is empty

- jdbc/pom.xml
- jdbc/src/main/java/org/apache/zeppelin/jdbc/JDBCInterpreter.java
- jdbc/src/main/java/org/apache/zeppelin/jdbc/kyuubi/BeelineInPlaceUpdateStream.java
- jdbc/src/main/java/org/apache/zeppelin/jdbc/kyuubi/KyuubiUtils.java
- jdbc/src/main/java/org/apache/zeppelin/jdbc/kyuubi/ProgressBar.java
- jdbc/src/main/resources/interpreter-setting.json
[Apache Kyuubi](https://kyuubi.apache.org) is a distributed and multi-tenant gateway to provide serverless SQL on Lakehouses. Namely, the latest [v1.9.1](https://kyuubi.apache.org/release/1.9.1.html) adds support for [Apache Spark 4.0.0-preview1](https://spark.apache.org/news/spark-4.0.0-preview1.html), integrated Zeppelin with Kyuubi unblocks users to adopt new Spark seamlessly. 
Kyuubi supports multiple computing engines, e.g. Spark, Flink, Hive, Trino, Doris, and multiple languages, e.g. SQL, Scala, PySpark.
This PR forces on the existing Spark SQL cases, adding support for:
- extracting logs
- jumping job web page
Feature
ZEPPELIN-6027
Manually tested, as the existing Hive has no UT either. …
> [ZEPPELIN-6027] Enhanced Integration with Apache Kyuubi

- bin/common.sh
In some cases, `$USER` is not available, this PR follows Hadoop[1] to enhance the `USER` evaluation.
For example, there is no `$USER` when login to docker
```
$ docker run -t -i ubuntu:latest
root@1dbeaefd6cd4:/# echo $USER
root@1dbeaefd6cd4:/# exit
```
[1] https://github.com/apache/hadoop/blob/rel/release-3.4.0/hadoop-common-project/hadoop-common/src/main/bin/hadoop-functions.sh#L893-L896
Improvement
ZEPPELIN-6028
Review.
> [ZEPPELIN-6028] Enhance default value assignment for ZEPPELIN_IDENT_STRING

- dev/common_release.sh
It was reported in ZEPPELIN-6029 that `zeppelin-0.11.1-bin-all.tgz` contains obsolete hidden files.
For every `$FILE` inside the Archive there is a second file called `._FILE`, e.g.
```
./lib/libthrift-0.13.0.jar
./lib/._libthrift-0.13.0.jar
```
I'm not sure how this happened, but according to https://apple.stackexchange.com/questions/280913/tar-excluding-files, `COPYFILE_DISABLE=1` should be used to address this issue.
Bug Fix
ZEPPELIN-6029
cc @jongyoul who is the release manager of Zeppelin 0.11.1
> [ZEPPELIN-6029] Set COPYFILE_DISABLE=1 for macOS tar

- zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/AbstractInterpreterTest.java
Resolves issue [ZEPPELIN-6031](https://issues.apache.org/jira/browse/ZEPPELIN-6031).
Currently, if someone runs tests locally and stop tests there will be left over config files, notebooks, etc.
It seems to happen more frequently with interpreter tests extending `AbstractInterpreterTest`.
This PR resolves by adding `forceDeleteOnExit()` hook so the files are deleted after JVM exit (even after test interruption)
Improvement
https://issues.apache.org/jira/browse/ZEPPELIN-6031
* Just Github Actions will do.
> [ZEPPELIN-6031] Clean up test directories even after unexpected exit of `AbstractInterpreterTest`

- zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
Fixes an issue where the Zeppelin Frontend was unable to create or update cron settings for any notebook. Fixes incorrect parsing of the roles submitted in the change request.
Bug Fix
-
(https://issues.apache.org/jira/browse/ZEPPELIN-6035)
Open Zeppelin Web UI
Open any Notebook
Click the Cron Icon
set any cron expression
Expected Behaviour:
- no Error should occur
- the new cron expression is saved in the notebook
- the notebook is automatically  run according to the cron expression
Image of the Error Message that is fixed with this MR
> [ZEPPELIN-6035] fix Cron setting for Notebook

- shell/Dockerfile
- shell/README.md
This PR adds a Dockerfile to build a shell interpreter. 
Although the interpreters are currently running as separate JVM processes, the existing structure confines them to a single machine, resulting in low availability. As a first step to address this, I've created a docker image for the shell interpreter using independent computing resources.
Since the current system wasn't designed with modular operation in mind, this PR involves some complexities in terms of configuration and testing. I'm planning to dockerize the other interpreters too, and I’ll try to iron out these kinks as I go.
Feature
* [ZEPPELIN-6034](https://issues.apache.org/jira/browse/ZEPPELIN-6034)
* Build and run the docker container
* Verify that the shell interpreter container communicates with the zeppelin server
* …
> [ZEPPELIN-6034] Write a Dockerfile for shell interpreter

- zeppelin-web/src/components/websocket/websocket-event.factory.js
- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/repo/VFSNotebookRepo.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/repo/VFSNotebookRepoTest.java
This PR reopens #4789. It was accidentally closed while resolving conflicts. @Reamer 
This PR modifies the notebook listing logic to exclude hidden files that start with `.`. 
This is because showing non-executable files, such as meta files, could confuse users, as seen in this issue [ZEPPELIN-6051](https://issues.apache.org/jira/browse/ZEPPELIN-6051).
Additionally I have enhanced the error popup message to be more specific, which appears when a user opens a notebook with parsing errors. I think it would be more helpful for users to recognize and resolve the issues on their own.
* Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-6051
* Create a notebook that can't be parsed and try to open it.
as-is
~~to-be~~
to-be
* Is there …
> [ZEPPELIN-6051] Skip the hidden files in notebook listing (reopen)

- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/repo/VFSNotebookRepo.java
- zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/repo/VFSNotebookRepoTest.java
This change was already merged into master with #4792.
This PR applies the changes to release-0.11 to avoid conflicts.
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-6051
* Create a notebook that can't be parsed and try to open it.
> [ZEPPELIN-6051] Skip the hidden files in notebook listing (branch-0.11)

- zeppelin-web/src/app/helium/helium.controller.js
- Relate : https://github.com/apache/zeppelin/pull/3449
- Thanks to above PR, using Helium got much safer. But there're still remaning vulnerability issues with Hellium package.
- If somebody makes malicious Hellium package, it can lead to serious consequences.
- `zeppelin-web` is dependent on `lodash@3.9.3` which supports escaping method `_.escape`
- I applied `_.escape(vulnerable-text)` to vulnerable text.
_You can see the HTML is not escaped and `<img>` tag has rendered_
_HTML is escaped and `<`, `>` has converted into HTML Entity which is safer_
Hot Fix
- N/A
- N/A
* Does the license files need to update? NO
* Is there breaking changes for older versions? NO
> [HOTFIX] Escaping vulnerable text  when modal opens

- zeppelin-zengine/src/main/java/org/apache/zeppelin/helium/HeliumBundleFactory.java
This PR upgrades the node, npm, and yarn versions of the HeliumBundleFactory in the zeppelin-server module to improve local development environment.
- node: v16.16.0
- npm: v8.11.0
- yarn: v1.22.0
Improvement
[ZEPPELIN-6050](https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-6050?filter=allissues)
1. Refer to [docs](https://github.com/apache/zeppelin/blob/master/docs/development/contribution/how_to_contribute_code.md) to configure `zeppelin-site.xml`.
2. Uncomment the property `zeppelin.helium.registry`
```xml
```
3. Start the zeppelin-server.
4. Go to `/#/helium` and install any visualizations or spells.(npm dependencies)
**Before**
**After**
> [ZEPPELIN-6050] Upgrade node, npm, yarn version of helium

- scripts/docker/interpreter/Dockerfile
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java
- zeppelin-plugins/launcher/docker/src/main/java/org/apache/zeppelin/interpreter/launcher/DockerInterpreterProcess.java
- zeppelin-plugins/launcher/docker/src/test/java/org/apache/zeppelin/interpreter/launcher/DockerInterpreterProcessTest.java
Several issues have been identified with the "docker" run mode that are causing it to function improperly. Below are the specific problems encountered:
- The base image version is outdated, currently at `0.8.0`, which is significantly behind the latest version.
- The URL for downloading Spark is not working, causing failures in the build process.
-  The `JAVA_HOME` variable from the host is unnecessarily being passed to the container, potentially causing conflicts with the intended Java environment inside the container.
- The `PATH` from the host is being propagated into the container, which may lead to unexpected behavior due to differing paths and binaries.
- The `ZEPPELIN_HOME` variable from the host is also being passed, which can interfere with the Zeppelin environment within the …
> [ZEPPELIN-6040] Run mode "docker" not working properly

- zeppelin-web-angular/src/app/pages/workspace/share/result/result.component.ts
In new UI, the results are rendered only after some interactions, such as a click on the other paragraph.
This PR addresses the issue by ensuring immediate rendering of the results when they are set in the `ngAfterViewInit` lifecycle hook. Previously, `markForCheck()` was used after setting `this.innerHTML`, which scheduled the component to be checked in the next change detection cycle but did not trigger an immediate update.
This has been changed to `detectChanges()` to force an immediate change detection, ensuring that the results are rendered right after they are set, without needing further user interaction.
Bug Fix
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/6063
- Run any paragraph in new UI
* Is there breaking …
> [ZEPPELIN-6063] Fix delay in paragraph results rendering in new UI

- docs/setup/security/shiro_authentication.md
Some links on the [Apache Shiro authentication page](https://zeppelin.apache.org/docs/latest/setup/security/shiro_authentication.html#1-enable-shiro:~:text=Realms%20are%20responsible,this%20documentation.) have been broken. It looks like the linked docs have been removed as the Shiro version was updated to 2.0. The 2.0 versions do not seem to provide apidocs for each realm, so I have removed these links to avoid confusion.
Bug Fix
Documentation
* https://issues.apache.org/jira/browse/ZEPPELIN-6065
* review
> [ZEPPELIN-6065] Remove broken links on the Apache Shiro authentication page

- zeppelin-web-angular/src/app/core/runtime-dynamic-module/ng-zorro-antd-module.ts
- zeppelin-web-angular/src/app/core/runtime-dynamic-module/ngmodule.decorator.ts
- zeppelin-web-angular/src/app/core/runtime-dynamic-module/runtime-dynamic-module.module.ts
The current issue is that the new UI fails to render dynamically created components at runtime, which causes the `%sh.terminal` interpreter to malfunction.
This problem occurs because Angular's AOT compiler removes decorators during the build process.([related issue](https://github.com/angular/angular-cli/issues/9306))
As far as I know, Angular does not support JIT compilation alongside the AOT compiler.
However, we need to render runtime dynamic components for compatibility reasons.
By Importing and re-exporting Angular core decorators, we can prevent the AOT compiler from removing them.
(https://github.com/angular/angular-cli/issues/9306#issuecomment-435404174)
I believe there are two possible solutions: either implementing this fix or turning off AOT compilation.
However, giving up the …
> [ZEPPELIN-6076] Fix rendering runtime dynamic components in new UI

- sparql/pom.xml
There are 1 security vulnerabilities found in org.apache.jena:jena-arq 3.12.0
- [CVE-2021-39239](https://www.oscs1024.com/hd/CVE-2021-39239)
Upgrade org.apache.jena:jena-arq from 3.12.0 to 4.2.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade org.apache.jena:jena-arq to 4.2.0

- sparql/pom.xml
Reverts apache/zeppelin#4507 because version 4.2.0 require JDK 11
> Revert "fix(sec): upgrade org.apache.jena:jena-arq to 4.2.0"

- jdbc/Dockerfile
- jdbc/README.md
- shell/Dockerfile
- shell/README.md
This PR adds a Dockerfile to build a JDBC interpreter container. It’s the second interpreter to be dockerized, after the shell interpreter (#4781). Like I said in the previous PR, the configuration and testing are a little complex at the moment. I plan to improve this in future work.
Feature
* [ZEPPELIN-6048](https://issues.apache.org/jira/browse/ZEPPELIN-6048)
* Build and run the docker container
* Verify that the jdbc interpreter container communicates with the zeppelin server
* Does the license files need to update? Yes
* Does this needs documentation? Yes. Docs added
> [ZEPPELIN-6048] Write a Dockerfile for jdbc interpreter image build

- zeppelin-web-angular/README.md
The `npm dev` command is miswritten in the current README file of zeppelin-web-angular. 
The correct command should be `npm run dev`, so I fixed it.
Additionally, I revised some inconsistent heading case usage throughout the file.
Improvement
* [ZEPPELIN-6081](https://issues.apache.org/jira/browse/ZEPPELIN-6081)
No tests are required as this is a documentation fix.
> [ZEPPELIN-6081] Fix Incorrect `npm dev` Command in README for zeppelin-web-angular

- bigquery/pom.xml
- bigquery/src/main/java/org/apache/zeppelin/bigquery/BigQueryInterpreter.java
- bigquery/src/main/resources/interpreter-setting.json
- docs/interpreter/bigquery.md
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-6080
*CI
local tests
> [ZEPPELIN-6080] Add support for bq single region dataset query

- zeppelin-web-angular/src/app/pages/workspace/interpreter/item/item.component.ts
There was an error in the new UI, that if dependencies of a interpreter was set in old UI, user could not see and edit the interpreter in new UI. More details about the issue can be seen in the comments [HERE](https://github.com/apache/zeppelin/pull/4727)
**Before**
Congifuring interpreter in old UI:
Not being able to interact with the configured interpreter in new UI:
**After**
Successfully can view and edit the configuration in new UI:
(Please don't mind the logs starting with '#####' and 'EXCLUSIONS' - I forgot to remove it when taking the screenshot)
Bug Fix
[ZEPPELIN-6079](https://issues.apache.org/jira/browse/ZEPPELIN-6079)
* Build and test - configure an interpreter via the old UI, and then switch to the new UI to verify that dependencies are now visible and editable.
* Does the …
> [ZEPPELIN-6079] Fix Interpreter Configuration not working in new UI

- Dockerfile
- dev/create_release.sh
- docs/quickstart/kubernetes.md
- pom.xml
- zeppelin-distribution/README.md
- zeppelin-distribution/build-infrastructure.md
- zeppelin-distribution/pom.xml
- zeppelin-distribution/src/assemble/distribution.xml
- zeppelin-integration/pom.xml
- zeppelin-server/pom.xml
This PR aims to canonicalize the binary distribution tarball name assembled by Maven.
Currently, the `./mvnw clean package -Pbuild-distr -DskipTests` produces `zeppelin-0.12.0-SNAPSHOT.tar.gz`, while the final release tarballs are `zeppelin-0.11.1-bin-all.tgz` and `zeppelin-0.11.1-bin-netinst.tgz`.
After this change, `./mvnw clean package -Pbuild-distr -DskipTests` produces `zeppelin-0.12.0-SNAPSHOT-bin.tgz`.
Improvement
ZEPPELIN-6073
Pass existing GHA and manually run maven command to package the binary tarball.
```
$ ./mvnw clean package -Pbuild-distr -DskipTests
```
```
...
[INFO] -------------< org.apache.zeppelin:zeppelin-distribution >--------------
[INFO] Building Zeppelin: Packaging distribution 0.12.0-SNAPSHOT        [64/64]
[INFO] --------------------------------[ pom …
```
> [ZEPPELIN-6073][BUILD] Canonicalize binary distribution tarball name

- zeppelin-integration/src/test/java/org/apache/zeppelin/integration/PersonalizeActionsIT.java
- zeppelin-integration/src/test/java/org/apache/zeppelin/integration/SparkParagraphIT.java
It seems that some integration tests are randomly failing due to timing discrepancies between rendering and verification.
To ensure that the values are validated after rendering is fully completed, I added a slight sleep time.
Before the fix, 7 out of 20 runs failed in my personal repository's Github Actions due to one or both the two tests.
However, after the fix, there were no failures from those two tests in 30 runs.
Bug Fix
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/6088
- CI
> [ZEPPELIN-6088] Fix some flaky tests in zeppelin-integration

- bin/interpreter.sh
- conf/zeppelin-env.sh.template
- docs/usage/interpreter/user_impersonation.md
The issue stems from the way the interpreter.sh script handles the ZEPPELIN_IMPERSONATE_CMD and constructs the command to be executed. Specifically, the command string passed to bash -c is not being properly formed as a single string, causing exec to fail when it tries to execute the impersonation command.
1. Command Construction: When ZEPPELIN_IMPERSONATE_CMD is set, the script attempts to build an array INTERPRETER_RUN_COMMAND that includes this command. However, if ZEPPELIN_IMPERSONATE_CMD is a string, it gets added as a single element to the array, leading to incorrect command parsing.
2. bash -c Behavior: The -c option in bash expects a single string argument that contains the command to execute. If this …
> [ZEPPELIN-6094] Fix broken impersonation

- dev/merge_zeppelin_pr.py
Zeppelin has `dev/merge_zeppelin_pr.py` that was borrowed from Spark, I would recommend committers use this script over the GitHub button to merge PR, which has some benefits:
1. Simplify the backport process
the tools will ask you to backport the commit to lower maintained branches after you merge a PR to master, if there are no conflicts, all things you need to do are just type a "branch name" that you want to backport.
2. Automatically update JIRA information
the script uses the python jira client to update JIRA ticket, for example, automatically closes the JIRA ticket after PR is merged, fills in the fixed versions, which is important to users to know the features/bug fixes applied to versions.
3. Better PR title, body, and "Signed-off-by" info
Before
After 
This PR syncs the change …
> [ZEPPELIN-6089][INFRA] Improve the merge PR script

- zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java
The misconfigured default `ZEPPELIN_ANGULAR_WAR` value is causing the failure to load the new UI web application files on development environment.
The new UI web apps are built into `ZEPPELIN_HOME/zeppelin-web-angular/dist/zeppelin`, but the default value lacks the `/zeppelin` postfix.
When developers run Zeppelin with `ZeppelinServer.main` method, it defaults to the incorrect `ZEPPELIN_ANGULAR_WAR` value, leading to failure to load the web apps.
*Note: This issue does not occur when Zeppelin is run using shell scripts in the `bin`, as they correctly set the `ZEPPELIN_ANGULAR_WAR` value.*
Bug Fix
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/6099
* Build Zeppelin
* Run Zeppelin using `ZeppelinServer.main` method and connect to `http://localhost:8080`
* Does the …
> [ZEPPELIN-6099] Fix default ZEPPELIN_ANGULAR_WAR value

- docs/interpreter/mongodb.md
- mongodb/src/main/resources/interpreter-setting.json
Since the release of MongoDB 5.0, the mongo shell has been deprecated and replaced by mongosh. Although MongoDB 5.0 was released in July 2021, Apache Zeppelin still uses mongo as the default shell. Updating the default shell from mongo to mongosh would help beginners adapt more easily and align with current MongoDB standards.
[Reference: MongoDB 5.0 Release Note](https://www.mongodb.com/docs/manual/release-notes/5.0/#shell-changes)
Improvement
[ZEPPELIN-6108]
* Run the MongoDB notebook
* Does this needs documentation? Y (update the docs)
> [ZEPPELIN-6108] Update MongoDB interpreter default shell value from mongo to mongosh

- mongodb/src/main/java/org/apache/zeppelin/mongodb/MongoDbInterpreter.java
This PR avoids an NPE when some MongoDB Interpreter configs are missing by replacing them with empty strings.
If certain MongoDB Interpreter configs, such as the username, password, or authenticationDatabase, are not entered, it throws an NPE. MongoDB allows logins without authentication when authentication is not enabled, so these configs are not always required. Since authentication is off by default in MongoDB, and these configs are also empty by default in Apache Zeppelin, this could be confusing for users.
And as you can see in [shell_extension.js](https://github.com/apache/zeppelin/blob/ac48cc2db1b55257230cae2c382961da2a9cf80d/mongodb/src/main/resources/shell_extension.js#L115), the MongoDB interpreter appears to be designed to skip authorization when the username is null. …
> [ZEPPELIN-6104] Fix NPE when some MongoDB Interpreter configs are missing

- zeppelin-web-angular/projects/zeppelin-sdk/src/interfaces/message-data-type-map.interface.ts
- zeppelin-web-angular/projects/zeppelin-sdk/src/interfaces/message-notebook.interface.ts
- zeppelin-web-angular/projects/zeppelin-sdk/src/interfaces/message-operator.interface.ts
- zeppelin-web-angular/projects/zeppelin-sdk/src/message.ts
- zeppelin-web-angular/src/app/pages/workspace/notebook/action-bar/action-bar.component.html
- zeppelin-web-angular/src/app/pages/workspace/notebook/action-bar/action-bar.component.ts
- zeppelin-web-angular/src/app/services/message.service.ts
Add missing button to action bar to reload note. This button exists in the old interface, but is missing in /next
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-6105
> [ZEPPELIN-6105] add 'reload note' button to the new interface

- zeppelin-web-angular/package.json
Specify the Node.js engine version below 17 in the `zeppelin-web-angular` package.json file to avoid errors related to Node.js 17+ and OpenSSL in Webpack.
If we upgrade the Angular version to 13+ in the future, we will be able to use Node.js 17+ as well.
[Reference: nodejs 17: digital envelope routines::unsupported · Issue #14532 · webpack/webpack](https://github.com/webpack/webpack/issues/14532)
Improvement
* [ZEPPELIN-6110]
1. Set your Node.js version to 17+
2. Execute `npm run postinstall` in `zeppelin-web-angular`
> [ZEPPELIN-6110] Specify the Node.js engine version below 17 in the `web-angular`

- docs/setup/basics/how_to_build.md
The ga-beacon link for Google Analytics tracking is broken. It is located on the [how_to_build](https://zeppelin.apache.org/docs/0.11.2/setup/basics/how_to_build.html#package) page.
For the following reasons, I removed this linke:
1. The broken link makes the page look poorly maintained. 
2. The ga-beacon doesn't seem to be supported anymore. 
3. The link doesn't seem intended to be on that page. Usually, it should be on the welcome page or across multiple pages. Since [this PR](https://github.com/apache/zeppelin/pull/1615/files#diff-180b6ccd4f65bde6bcd6ce9e7d6872d768d3b18c2e05f8faad36ff6279199ce1R343) relocated the link, I think it might have been unintentional.
Documentation
* ZEPPELIN-6114
* Build documentation
* Is there breaking changes for …
> [ZEPPELIN-6114] Remove broken link for Google Analytics tracking

- bin/interpreter.sh
This PR reverts commit dd08a3966ef3b0b40f13d0291d7cac5ec3dd9f9c which was merged with #4715
I have set the environment variable `ZEPPELIN_INTP_CLASSPATH_OVERRIDES`, which now no longer works due to the change.
I have set the environment variable to the value `/usr/share/java/*`, which in my opinion represents a valid classpath.
`printf %q "/usr/share/java/*"` results in `/usr/share/java/\*`, which is no longer a valid classpath.
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-6103
> [ZEPPELIN-6103] Revert "[HOTFIX] Escape envs when using `.conf` (#4715)"

- dev/merge_zeppelin_pr.py
This PR fixes some issues in the `dev/merge_zeppelin_pr.py` to make it smarter in suggesting "backport branch" and "fixed versions".
1. improve the `x.y.z` version comparing
For versions: `["0.9.1", "0.10.1", "0.11.3", "0.12.0"]`
Previously, it was a simple string comparison, so the desc sorted result is `["0.9.1", "0.12.0", "0.11.3", "0.10.1"]`; this PR changes it by interpreting each x, y, z as an int value and comparing sequence, thus the desc sorted result is `["0.12.0", "0.11.3", "0.10.1", "0.9.1"]`
2. improve the `branch-x.y` branch comparing
similar to 1, `branch-0.10` is higher than `branch-0.9`
3. dedup `found_versions`
before
```
Enter comma-separated fix version(s) [0.12.0,0.12.0]:
```
after
```
Enter comma-separated fix version(s) [0.12.0]:
```
Improvement
ZEPPELIN-6089 …
> [ZEPPELIN-6089][INFRA][FOLLOWUP] Consider multiple digits when comparing version numbers

- .github/workflows/core.yml
- .github/workflows/frontend.yml
CI start failing at "Setup conda environment" because of
> October 2024: The Mambaforge installers will refuse to install during several pre-specified date ranges (i.e., ["brownouts"](https://en.wikipedia.org/wiki/Brownout_(software_engineering))) in order to encourage users to switch to Miniforge. These dates are
> - Every two weeks in October 2024 (2024-10-01, 2024-10-15)
https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/
The fix refers to https://github.com/conda-incubator/setup-miniconda/pull/360
Bug Fix
ZEPPELIN-6117
Pass GHA.
> [ZEPPELIN-6117][INFRA] Remove deprecated Mambaforge

- Dockerfile
- docs/setup/basics/how_to_build.md
- k8s/zeppelin-server.yaml
- pom.xml
- rlang/pom.xml
- scripts/docker/zeppelin-interpreter/env_python_3_with_R.yml
- spark/interpreter/pom.xml
- spark/pom.xml
- spark/scala-2.12/pom.xml
- spark/scala-2.13/pom.xml
Currently, Zeppelin supports Spark 3.3, 3.4(default), and 3.5. This PR bumps the default Spark version to 3.5.3, corresponding Scala deps are upgraded too.
Improvement
ZEPPELIN-6119
Pass GHA.
> [ZEPPELIN-6119] Bump default Spark version to 3.5.3

- dev/checkout_zeppelin_pr.sh
(Reopening to link this github PR issues to the jira issue)
The `dev/checkout_zeppelin_pr.sh` script is useful for locally checking out PR commits.
Currently, it fetches the PR and checks out a new branch.
However, if the script is run while already on the target branch, the updates are not reflected because `git checkout` does not move the `HEAD` when the current branch is already checked out.
To resolve this, the script has been updated to use `git pull` instead when the current branch is already checked out.
Improvement
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-6125
* Outline any manual steps to …
> [ZEPPELIN-6125] Enable updates on the same branch using dev/checkout_zeppelin_pr.sh

- zeppelin-interpreter/pom.xml
when building with `-Pinclude-hadoop`, `com.google.code.findbugs:jsr305`'s scope becomes runtime thus failing the build.
Bug Fix
ZEPPELIN-6101
tested with the command `./mvnw clean package -Pbuild-distr -DskipTests -Pinclude-hadoop`
> [ZEPPELIN-6101][FOLLOWUP] Fix build with profile include-hadoop

- conf/zeppelin-site.xml.template
- docs/quickstart/explore_ui.md
- docs/setup/operation/configuration.md
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java
- zeppelin-server/src/main/java/org/apache/zeppelin/server/IndexHtmlServlet.java
- zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java
- zeppelin-server/src/test/java/org/apache/zeppelin/server/IndexHtmlServletTest.java
- zeppelin-web-angular/package.json
- zeppelin-web-angular/src/app/share/header/header.component.html
- zeppelin-web-angular/src/app/share/header/header.component.ts
- zeppelin-web-angular/src/index.html
- zeppelin-web/src/components/navbar/navbar.controller.js
- zeppelin-web/src/components/navbar/navbar.html
- zeppelin-web/src/index.html
This PR introduces a new configuration option `zeppelin.default.ui` to set the default UI for Zeppelin.
The available options for this setting are `new` and `classic`.
By default, the value is set to `new`, meaning the new UI will be served at the root path (`"/"`), while the classic UI will be available at `"/classic"`.
If the configuration is set to `classic`, the classic UI will be served at `"/"`, and the new UI at `"/new"`.
Improvement
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN/6085
- Testing the `new` option :
- Set the `zeppelin.default.ui` config to `new` (the default).
- Verify that the new UI is served at the root (`"/"`) and the classic UI is available at `"/classic"`. …
> [ZEPPELIN-6085] Add configuration option for setting the default UI

- zeppelin-web/pom.xml
This PR removes the Hadoop dependencies in the zeppelin-web.war file. At the moment it is not clear to me how this behavior came about in Zeppelin.
Build Command: `./mvnw clean package -DskipTests -Pinclude-hadoop -Pweb-classic -Pweb-dist -pl zeppelin-web -am`
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-6126
Before:
```
15:53 $ ls -lh zeppelin-web/target/
insgesamt 47M
drwxrwxr-x  3 pdallig pdallig 4,0K Okt  9 15:51 classes
drwxrwxr-x  2 pdallig pdallig 4,0K Okt  9 15:51 maven-archiver
drwxrwxr-x  3 pdallig pdallig 4,0K Okt  9 15:51 maven-shared-archive-resources
drwxrwxr-x  3 pdallig pdallig 4,0K Okt  9 15:51 test-classes
drwxrwxr-x 11 pdallig pdallig 4,0K Okt  9 15:51 zeppelin-web-0.12.0-SNAPSHOT
-rw-rw-r--  1 pdallig pdallig  47M Okt  9 15:51 …
```
> [ZEPPELIN-6126] Remove hadoop dependencies out of the final zeppelin-web.war

- zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/code-editor/code-editor.component.ts
https://github.com/user-attachments/assets/6204b6f5-409e-4cd1-8901-eb09114e9ded
Steps to reproduce:
1. Make a new Paragraph.
2. Refresh the page.
3. Click on the paragraph to make the cursor blink.
[How to solve]
https://github.com/apache/zeppelin/blob/bdf5b067b6bdde2614b98a6a3f6a7b5d6637e57c/zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/code-editor/code-editor.component.ts#L62
Set default value of editor's height
Bug Fix
* [[ZEPPELIN-6096](https://issues.apache.org/jira/browse/ZEPPELIN-6096)]
> [ZEPPELIN-6096] Cursor appears cut off in Notebook editor

- zeppelin-web-angular/src/app/app-message.interceptor.ts
If I broke notebook's(*.zepl) JSON structure I can get error message like below.
There are two kind of problems.
1. Same error message shows twice.
2. Word break CSS style is not applied yet so it looks quite weird.
So I fixed it correct way.
[How to solve]
1. Check [/zeppelin-web-angular/src/app/pages/workspace/notebook/notebook.component.ts](https://github.com/apache/zeppelin/blob/bdf5b067b6bdde2614b98a6a3f6a7b5d6637e57c/zeppelin-web-angular/src/app/pages/workspace/notebook/notebook.component.ts) file and found [L392](https://github.com/apache/zeppelin/blob/bdf5b067b6bdde2614b98a6a3f6a7b5d6637e57c/zeppelin-web-angular/src/app/pages/workspace/notebook/notebook.component.ts#L392), [L396](https://github.com/apache/zeppelin/blob/bdf5b067b6bdde2614b98a6a3f6a7b5d6637e57c/zeppelin-web-angular/s …
> [ZEPPELIN-6097] Suppress duplicated error popup and fix broken CSS

- bin/common.sh
When setting `ZEPPELIN_ANGULAR_WAR`, it should check for the `${ZEPPELIN_HOME}/zeppelin-web-angular/dist/zeppelin` directory.
However, it currently checks for the `${ZEPPELIN_HOME}/zeppelin-web/dist` directory, causing an issue where the new UI load fails if the classic UI is not built.
Bug Fix
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-6127
- Clear classic UI `dist` directory. (remove `${ZEPPELIN_HOME}/zeppelin-web/dist` directory)
- Build without classic UI profile (`./mvnw package -DskipTests -Pinclude-hadoop`)
- Run Zeppelin with daemon script. (`./bin/zeppelin-daemon.sh start`)
- Ensure the new UI loads properly at `http://localhost:8080/`.
* Does this needs …
> [ZEPPELIN-6127] Fix setting incorrect ZEPPELIN_ANGULAR_WAR value

- .github/workflows/core.yml
- livy/src/test/java/org/apache/zeppelin/livy/LivyInterpreterIT.java
Migrate the Livy test from Spark 2.4 with Java 8 to Spark 3.2 with Java 11.
There is a failed test caused by a classloader issue, likely a Livy-side issue, temporarily disable it.
```
Error:  Failures: 
Error:    LivyInterpreterIT.testLivyTutorialNote:689 %text org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0) (localhost executor driver): java.lang.ClassCastException: class Bank cannot be cast to class Bank (Bank is in unnamed module of loader org.apache.spark.repl.ExecutorClassLoader @6e7a7cff; Bank is in unnamed module of loader scala.tools.nsc.interpreter.IMain$TranslatingClassLoader @67f10f45)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodege …
```
> [ZEPPELIN-6134] Test Livy 0.8 and Spark 3.2 with Java 11

- .github/workflows/core.yml
This pull request removes the test with JDK 8. I have kept the JDK matrix to make it easier to switch to the next JDK later.
This pull request also drops python 3.7 & 3.8 tests for the `python`,`rlang` and `zeppelin-jupyter` interpreter. Please note that current python 3.7 and 3.8 are end of life. https://devguide.python.org/versions/
Improvement
- https://issues.apache.org/jira/browse/ZEPPELIN-6090
* CI
> [ZEPPELIN-6090] Drop JDK8 from CI

- docs/development/contribution/how_to_contribute_code.md
- pom.xml
Small change, big effect. This pull request changes the Maven compiler setting to JDK 11.
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-6136
* CI
* Is there breaking changes for older versions? YES
> [ZEPPELIN-6136] Java release to 11

- bigquery/src/main/java/org/apache/zeppelin/bigquery/BigQueryInterpreter.java
- build-tools/src/main/resources/zeppelin/checkstyle.xml
- elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/ElasticsearchInterpreterTest.java
- java/src/main/java/org/apache/zeppelin/java/JavaInterpreter.java
- pom.xml
This pull request updates the Apache parent version. We benefit significantly from plugin updates and can clean up our own `pom.xml`.
plugin updates:
maven-antrun-plugin - 1.8 -> 3.1.0
maven-assembly-plugin - 3.7.1 -> 3.7.1
maven-clean-plugin - 3.1.0 -> 3.4.0
maven-compiler-plugin - 3.8.1 -> 3.13.0
maven-dependency-plugin - 3.1.2 -> 3.7.1
maven-deploy-plugin - 2.8.2 -> 3.1.2
maven-enforcer-plugin - 3.0.0-M3 -> 3.5.0
maven-gpg-plugin - 1.6 -> 3.2.4
apache-rat-plugin - 0.13 -> 0.16.1
surefire & failsafe version - 3.2.2 -> 3.3.0
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-6138
* CI
> [ZEPPELIN-6138] Update Apache Parent

- shell/src/main/java/org/apache/zeppelin/shell/TerminalInterpreter.java
- shell/src/main/java/org/apache/zeppelin/shell/terminal/TerminalThread.java
- shell/src/main/java/org/apache/zeppelin/shell/terminal/websocket/TerminalSessionConfigurator.java
- shell/src/test/java/org/apache/zeppelin/shell/TerminalInterpreterTest.java
- shell/src/test/java/org/apache/zeppelin/shell/terminal/TerminalSocketTest.java
This PR adds an Origin check to ensure that WebSocket connections are initiated from trusted sources only.
By validating the `Origin` header in the initial WebSocket handshake, we can prevent unauthorized or malicious websites from establishing WebSocket connections with our server.
Changes:
- Added server-side validation of the `Origin` header during WebSocket connection requests.
Other security enhancements may be needed and can be handled in future iterations.
Improvement
> [NO-ISSUE] Implement Origin check for terminal interpreter WebSocket connections

- flink/flink-scala-2.12/pom.xml
- flink/pom.xml
- spark/interpreter/pom.xml
- spark/pom.xml
- spark/spark-scala-parent/pom.xml
The Maven clean goal does not remove some interpreter files in `interpreter/` directory as expected.
Specifically, the `spark` and `flink` interpreters are not cleaned.
This happens because when extending the `pom.xml` in the `pom.xml` of these interpreters, they lack the `interpreter.name` property.
As a result, the clean target directory configured in `zeppelion-interpreter-parent` was not properly resolved before.
Bug Fix
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-6135
- Build Zeppelin
- Clean Zeppelin and check if all interpreters are removed in `interpreter/`
> [ZEPPELIN-6135] Fix clean goal not removing interpreter/ output(Spark,Flink)

- jdbc/src/main/java/org/apache/zeppelin/jdbc/JDBCInterpreter.java
- jdbc/src/test/java/org/apache/zeppelin/jdbc/JDBCInterpreterTest.java
Add some validation check conditions to existing url validator in jdbc interpreter. So now it can check URLs with the conditions below if it has an unallowable configuration.
- UTF-8 encoded
Improvement
[ZEPPELIN-6095](https://issues.apache.org/jira/browse/ZEPPELIN-6095)
Input the url with unallowable configurations in UTF-8 encoded in JDBC type interpreter.  Then run the command in notebook and see if the command is blocked from running.
> [ZEPPELIN-6095] validate decoded url in jdbc interpreter

- zeppelin-web-angular/src/app/pages/workspace/interpreter/interpreter.component.ts
The interpreter search in the new UI doesn’t ignore case sensitivity, unlike the old UI. I updated it to be case-insensitive in the new UI as well for better UX.
Improvement
[ZEPPELIN-6147](https://issues.apache.org/jira/browse/ZEPPELIN-6147/)
* Ensure interpreters can be searched case-insensitively
**old ui**
**new ui (before update)**
> [ZEPPELIN-6147] Make interpreter searching case-insensitive in new ui

- zeppelin-web-angular/src/app/share/note-import/note-import.component.html
Currently, in new UI, it's not that easy to import notes fron .zpln files, since by default file importer only looks for .json files. The bug was reproduced in both Win10 and MacOs
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-6146
> [ZEPPELIN-6146] Replace 'application/zpln' with '.zpln' in 'accept' attribute of file importer

- zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
This involves revising the description of the runParagraph method and adding clear logs for each step.
Improvement
* https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-6140
* Debugging
> [ZEPPELIN-6140] Add logs to the runParagraph method

- README.md
- zeppelin-web-angular/src/app/pages/workspace/home/home.component.html
- zeppelin-web/src/app/home/home.html
I recommend that clicking on Issues Tracking in the Zeppelin Web UI redirects to a page where all issues are sorted.
Feature
* https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-6141
* Click Issues Tracking after build
Zeppelin Web UI
Before
After
> [ZEPPELIN-6141] Update the link to the page where all issues are sorted

- elasticsearch/src/main/java/org/apache/zeppelin/elasticsearch/client/HttpBasedClient.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/UpdateInterpreterSettingRequest.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/message/UpdateInterpreterSettingRequestTest.java
There was an issue where the port was treated as a string and included `.0` when modifying the port of the Elasticsearch interpreter.
Bug Fix
* https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-6131
* Zeppelin project build and run
```bash
./mvnw clean package -DskipTests
```
* Add a test index and test data to Elasticsearch
```bash
curl -X PUT "http://localhost:9200/customer?pretty"
curl -X \
PUT "localhost:9200/customer/_doc/1" \
-H 'Content-Type: application/json' \
-d'
{
"field_1": "value_1"
}'
```
* Modify the Elasticsearch interpreter type and port
elasticsearch.client.type: transport -> http
elasticsearch.port: 9300 -> 9200
* Previous configuration
* New configuration
* Create a Zeppelin notebook and execute a paragraph
```bash
%elasticsearch
get /customer/_doc/1
``` …
> [ZEPPELIN-6131] Update Interpreter to Store Values as Integers When Applicable

- shell/src/main/java/org/apache/zeppelin/shell/terminal/service/TerminalService.java
- shell/src/main/java/org/apache/zeppelin/shell/terminal/websocket/TerminalSocket.java
- shell/src/main/resources/html/js/index.js
This PR removes `TERMINAL_INIT` to simplify the code. `TERMINAL_INIT`, one of the WebSocket message types in the terminal interpreter, looks unused and redundant with `TERMINAL_READY`
Refactoring
https://issues.apache.org/jira/browse/ZEPPELIN-6145
* Execute terminal interpreter
> [ZEPPELIN-6145] Remove useless message type in Terminal Interpreter

- bin/zeppelin.sh
Obviously, `*_HOME` should be respected if they are present, otherwise fallback to find the command in `PATH`.
Improvement
ZEPPELIN-6150
Manually tested on a dev env, there are multiple Hadoop clients installed in one machine, and `hadoop` is not available in `PATH`, now I can set `HADOOP_HOME` to allow Zeppelin start.
* Does the license files need to update? no
* Is there breaking changes for older versions? might be
> [ZEPPELIN-6150] `zeppelin.sh` shall respect HADOOP_HOME to find `hadoop` command

- conf/zeppelin-env.sh.template
- conf/zeppelin-site.xml.template
- docs/setup/operation/configuration.md
- zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/RemoteInterpreterEventServer.java
This PR introduces the `ZEPPELIN_EVENT_SERVER_PORT` configuration option.
When this option is set, the Event server that communicates with interpreters will listen on the specified port.
The `ZEPPELIN_EVENT_SERVER_PORT` option takes precedence over `ZEPPELIN_SERVER_RPC_PORTRANGE` option.
If `ZEPPELIN_EVENT_SERVER_PORT` is set, the `ZEPPELIN_SERVER_RPC_PORTRANGE` range will be ignored.
This option is particularly useful when running individual Zeppelin components in container orchestration environments like Kubernetes.
By explicitly specifying the port, it allows for a more declarative and clearer configuration of service resources compared to `ZEPPELIN_SERVER_RPC_PORTRANGE`.
Improvement
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-6143
* Run Zeppelin with and …
> [ZEPPELIN-6143] Add Interpreter Event Server Port configuration option

- docs/quickstart/kubernetes.md
- docs/setup/deployment/flink_and_spark_cluster.md
- flink/flink-scala-2.12/pom.xml
- rlang/pom.xml
- scripts/docker/interpreter/Dockerfile
- scripts/docker/spark-cluster-managers/spark_yarn_cluster/Dockerfile
- scripts/docker/zeppelin/bin/Dockerfile
- spark/interpreter/pom.xml
- spark/pom.xml
- testing/downloadLivy.sh
- testing/downloadSpark.sh
Current artifacts available in CDN (`dlcdn.apache.org`) may get removed without notice when new releases appear.  To avoid broken links, build scripts contain permanent addresses from `archive.apache.org`.  But download from `archive.apache.org` may be slow:
```
Thu, 05 Dec 2024 08:39:53 GMT [INFO] --- download:1.6.0:wget (download-sparkr-files) @ r ---
Thu, 05 Dec 2024 08:39:54 GMT Warning:  No signatures were supplied, skipping file validation
Thu, 05 Dec 2024 08:39:54 GMT [INFO] Read Timeout is set to 60000 milliseconds (apprx 1 minutes)
Thu, 05 Dec 2024 08:45:46 GMT [INFO] Expanding: /home/runner/work/zeppelin/zeppelin/rlang/target/spark-3.5.3-bin-without-hadoop.tgz into /home/runner/work/zeppelin/zeppelin/rlang/target
```
Apache Infra's [`closer.lua` …
> [ZEPPELIN-6157] Download artifacts from CDN if available

- LICENSE
The Apache 2.0 license on the website shows that it ends after "END OF TERMS AND CONDITIONS" https://www.apache.org/licenses/LICENSE-2.0
This text exists because it's been mistakenly copied and pasted from https://www.apache.org/licenses/LICENSE-2.0.txt where it includes placeholder text and the intent seems to be reproducing the application instructions as seen on https://www.apache.org/licenses/LICENSE-2.0 rather than as text that's intended to be included in the license.
The text removed in this PR diverges slightly from the text on https://www.apache.org/licenses/LICENSE-2.0#apply
> How to apply the Apache License to your work
>
> Include a copy of the Apache License, typically in a file called LICENSE, in your work, and consider also including a NOTICE file that references the …
> [MINOR] Remove extra text from license

- zeppelin-plugins/launcher/k8s-standard/src/main/java/org/apache/zeppelin/interpreter/launcher/K8sUtils.java
- zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/K8sUtilsTest.java
Fix the problem with k8s interpreter service creating
Bug Fix
* https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-6168
Compiled and tested manually.
* No
* No
* No
> [ZEPPELIN-6168] Fix k8s interpreter service name removing all dots from pod name

- k8s/interpreter/100-interpreter-spec.yaml
interpreters that are not in spark group skip imagePullSecrets field so that container image pulling get failed
Bug Fix
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-6176
manual test done (python interpreter with spark connect)
> [ZEPPELIN-6176] imagePullSecrets is skipped in interpreter other than spark

- docs/interpreter/hbase.md
- hbase/pom.xml
- hbase/src/main/java/org/apache/zeppelin/hbase/HbaseInterpreter.java
- hbase/src/main/resources/interpreter-setting.json
- hbase/src/test/java/org/apache/zeppelin/hbase/HbaseInterpreterTest.java
- zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/HBaseIntegrationTest.java
- zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/HBaseIntegrationTest172.java
- zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/HBaseIntegrationTest2418.java
- zeppelin-test/src/main/java/org/apache/zeppelin/test/DownloadUtils.java
- zeppelin-test/src/test/java/org/apache/zeppelin/test/DownloadUtilsTest.java
Currently in Zeppelin HBase interpreter does not support HBase 2.x ruby syntax.
This patch added hbase-2.x support.
This closes ZEPPELIN-6163
Improvement
[ZEPPELIN-6163](https://issues.apache.org/jira/browse/ZEPPELIN-6163)
Compiled and tested manually.
> [ZEPPELIN-6163] HBase interpreter supports hbase-2.x

- elasticsearch/src/main/java/org/apache/zeppelin/elasticsearch/ElasticsearchInterpreter.java
- elasticsearch/src/main/resources/interpreter-setting.json
The following improvements have been made to the Elasticsearch interpreter:
- Updated default interpreter settings for better clarity and consistency.
- Ensured accurate property types and added missing environment variable mappings.
- Improved descriptions for better user understanding in the Zeppelin UI.
- Changed default port to 9200 and client type to http to align with Elasticsearch 8.x, where the Transport Client has been removed.
- Modified the help command output to improve readability and accuracy.
- Reformatted command usage examples.
- Fixed grammar and clarified parameter descriptions.
These changes enhance the usability of the interpreter and make it easier for users to configure and understand how to interact with Elasticsearch through Zeppelin.
Refactoring
* …
> [ZEPPELIN-6188] Improve Elasticsearch interpreter config and help message

- .github/workflows/core.yml
- .github/workflows/frontend.yml
**Problem Summary:**
The interpreter-test-non-core (11) job within the core GitHub Actions workflow occasionally fails during the Conda environment setup phase. These failures are non-deterministic (flaky) and do not correlate with specific code changes, indicating an environment-related root cause.
**Details:**
The failure typically occurs when resolving dependencies using Conda, with the following error observed:
```bash
python: /croot/libsolv-suite.../rules.c:261: solver_addrule: Assertion `!p2 && d > 0' failed.
```
This assertion failure is triggered by Conda's dependency resolver (libsolv) when it encounters unresolved or conflicting constraints.
Previously, the workflow used channel-priority: true, which corresponds to flexible priority mode. This allowed mixing packages from both …
> [ZEPPELIN-6194] Fix flaky Conda environment setup by using strict channel priority in GitHub Actions

- docs/usage/other_features/cron_scheduler.md
This PR adds description of another condition to enable Cron feature in documentation.
It is hard to know that is is required to configure Shiro authentication to enable Cron feature.
Documentation
* [ZEPPELIN-3271]
* `bundle exec jekyll serve --watch` and check the documentation updated.
> [ZEPPELIN-3271] add shiro setup for cron feature in docs

- zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
- zeppelin-server/src/test/java/org/apache/zeppelin/service/NotebookServiceTest.java
This PR addresses an issue in `NotebookService` where the notebook path validation only performs a single decoding pass.
This allowed a malicious user to bypass validation by double-encoding the `".."` token.
By implementing the repeated decoding, we can prevent this bypass.
Additionally, to prevent excessive decoding attempts, a maximum limit on the number of decoding attempts has been added.
Hot Fix
https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-6190
* CI
* There may be minor compatibility issues if a user relies on multiple encoded paths, but this is unlikely in realistic scenarios.
> [ZEPPELIN-6190] Prevent directory escape bypass through repeated URL decoding

- zeppelin-server/pom.xml
- zeppelin-server/src/main/java/org/apache/zeppelin/service/ShiroAuthenticationService.java
- zeppelin-server/src/test/java/org/apache/zeppelin/service/ShiroAuthenticationServiceTest.java
This PR fixes a broken feature where getUserList fails when using JdbcRealm for Shiro authentication.
The previous PR addressing SQL injection introduced an error that prevents getUserList from working correctly with JdbcRealm. As a result, users are unable to set notebook permissions.
Ref: #4676
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-3725
* https://issues.apache.org/jira/browse/ZEPPELIN-6186
Added new unit test should be passed
* `./mvnw clean package -pl zeppelin-server -am`
Verify in UI
* Go to notebook permission settings
* Type username and see if username listed
> [ZEPPELIN-6186] fix searching user using JdbcRealm

- zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/paragraph.component.ts
This PR fixes an issue that prevents entering shortcut characters in input fields.
When using a dynamic input field, characters like 'l', 'b', etc., are treated as shortcuts and cannot be entered.
This fix prevents shortcut actions from being triggered when the focused element is an input field.
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-6185
* Create new notebook using dynamic input field 
* Enter 'l' character and see if it is not working as shortcut(toggling line numbers)
> [ZEPPELIN-6185] fix prevent shortcut working in input field

- elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/action/AggWrapperTest.java
- elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/action/HitWrapperTest.java
- elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/client/ElasticsearchClientTypeBuilderTest.java
- elasticsearch/src/test/java/org/apache/zeppelin/elasticsearch/client/ElasticsearchClientTypeTest.java
This PR improves the test coverage for the Elasticsearch interpreter module by:
- Refactoring and enhancing the existing unit tests in `ElasticsearchClientTypeTest` and `ElasticsearchClientTypeBuilderTest`
- Adding new unit tests for `AggWrapper` and `HitWrapper`
These changes help ensure better reliability and maintainability of Elasticsearch-related components in Apache Zeppelin.
Improvement
* Jira: https://issues.apache.org/jira/browse/ZEPPELIN-6196
The following test classes were added or modified:
- `ElasticsearchClientTypeTest`
- `ElasticsearchClientTypeBuilderTest`
- `AggWrapperTest`
- `HitWrapperTest`
You can verify these tests by running:
`./mvnw -pl elasticsearch test`
N/A
* Does …
> [ZEPPELIN-6196] Improve and Add Unit Tests for Elasticsearch Client and Wrappers

- zeppelin-web-angular/src/app/pages/workspace/job-manager/job/job.component.html
URLs to notebook page are set wrong in job manager page
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-6206
- Enable cron and job manager configurations and check a links in the page
- `zeppelin.jobmanager.enable` : `true`
- `zeppelin.notebook.cron.enable`: `true`
- `zeppelin.notebook.cron.folders` : `/`
> [ZEPPELIN-6206] Fix notebook paths in job manager page

- NOTICE
This PR updates the copyright year in the NOTICE file from 2024 to 2025.
Since the project has received contributions in 2025, this update ensures that the legal documentation remains accurate and consistent with ASF guidelines.
No functional changes are introduced—this is a documentation-only update.
Documentation
* Jira: https://issues.apache.org/jira/browse/ZEPPELIN-6219
* No testing is required as this change only updates static text in the NOTICE file.
N/A
> [ZEPPELIN-6219] Update copyright year in NOTICE file from 2024 to 2025

- neo4j/src/main/resources/interpreter-setting.json
This PR improves the property descriptions in interpreter-setting.json for the Neo4j interpreter.
Some of the original descriptions contained typos, grammatical issues, or unclear phrasing.
The updated descriptions are now clearer, more consistent, and easier for users to understand when configuring the interpreter in Zeppelin.
This is a documentation-only change and does not affect any functionality.
Documentation
* Jira: https://issues.apache.org/jira/browse/ZEPPELIN-6222 
No functional testing is required.
You can verify that the updated descriptions appear correctly in the interpreter setting UI.
N/A
> [ZEPPELIN-6222] Fix typos and improve clarity in Neo4j interpreter configuration descriptions

- docs/quickstart/tutorial.md
Currently, download link of `bank.zip` file in [tutorial page](https://zeppelin.apache.org/docs/0.12.0/quickstart/tutorial.html) is broken.
The root cause is a change in the URL for the UCI Machine Learning dataset. The previous link, http://archive.ics.uci.edu/ml/machine-learning-databases/00222/bank.zip, is no longer valid. 
The new dataset for the same ID (222) is now located at https://archive.ics.uci.edu/dataset/222/bank+marketing.
Additionally, `bank.zip` is no longer offered as a standalone file. It is now nested inside a `bank+marketing.zip` archive.
This PR updates the tutorial to:
* Replace the broken link with the new, correct URL for the `bank+marketing.zip` file.
* Add a clear instruction for users to first unzip the main `bank+marketing.zip` archive to find and use the …
> [ZEPPELIN-6199] Fix tutorial document file download not working

- zeppelin-web-angular/src/app/pages/workspace/notebook/add-paragraph/add-paragraph.component.less
This PR fixes a simple CSS issue.
The "Add Paragraph" button in the Notebook was partially hidden.  
Fixed by repositioning the button.
Bug Fix
[ZEPPELIN-6230]
* Build and run zeppelin web locally
**as-is**
**to-be**
> [ZEPPELIN-6230] "Add Paragraph" button should not be hidden in Notebook.

- .github/workflows/stale.yml
This pull request introduces a new workflow for managing stale pull requests. The workflow is designed to automatically close pull requests that have been inactive for over a year.
Improvement
MINOR
Check CI logs
> [MINOR] Add GitHub Action to close stale PRs

- zeppelin-server/src/main/java/org/apache/zeppelin/rest/filter/CacheControlFilter.java
- zeppelin-server/src/main/java/org/apache/zeppelin/server/RestApiApplication.java
- zeppelin-server/src/test/java/org/apache/zeppelin/rest/filter/CacheContolFilterTest.java
This pull request sets the no cache header for all Zeppelin API calls.
* Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-6213
* CI
Before - no cache header
After - with cache header
> [ZEPPELIN-6213] Add Cache-Control Header to API Calls

- zeppelin-test/src/main/java/org/apache/zeppelin/test/DownloadRequest.java
This PR removes unused overloaded constructors in the DownloadRequest class located at:
zeppelin/zeppelin-test/src/main/java/org/apache/zeppelin/test/DownloadRequest.java.
Specifically, the constructor:
```
public DownloadRequest(URL url, int retries)
```
is not used anywhere within the Zeppelin codebase or its test suite. Removing these unused constructors simplifies the class and reduces maintenance complexity, without affecting any functional behavior.
As this constructor was removed, other constructors that were only used by it have also been removed accordingly.
Refactoring
* Open an issue on Jira. [ZEPPELIN-6220](https://issues.apache.org/jira/browse/ZEPPELIN-6220)
* Outline any manual steps to test the …
> [ZEPPELIN-6220] Remove unused constructor in DownloadRequest.class

- file/src/main/java/org/apache/zeppelin/file/HDFSFileInterpreter.java
In the following file [zeppelin/file/src/main/java/org/apache/zeppelin/file/HDFSFileInterpreter.java](https://github.com/apache/zeppelin/blob/91f091e287b94295ec7f10254b4f4ac800209899/file/src/main/java/org/apache/zeppelin/file/HDFSFileInterpreter.java#L180)
The Character constructor is deprecated in Java 9 and later, recommending the use of the static factory method Character.valueOf() instead.
This change's objective is to update the code to use the modern recommended approach.
As-is
```
if (args.flags.contains(new Character('l'))) {
```
To-be
```
if (args.flags.contains(Character.valueOf('l'))) {
```
Also, Changed single word's type from **""** -> **''**
Refactoring
* Open an issue on [Jira](https://issues.apache.org/jira/browse/ZEPPELIN-6246)
* Strongly recommended: add automated unit …
> [ZEPPELIN-6246] Replace deprecated Character constructor

- SECURITY-README.md
This PR improves the grammar, clarity, and structure of SECURITY-README.md, which explains how Shiro authentication works in Apache Zeppelin.
It fixes typos, updates awkward or outdated phrases, and improves the consistency of terminology and punctuation. The documentation link has also been updated to point to the stable 0.12.0 release.
These changes make the document easier to read and maintain, while providing clearer guidance to users setting up security in Zeppelin.
Documentation
* Jira: https://issues.apache.org/jira/browse/ZEPPELIN-6223
N/A
* Does this needs …
> [ZEPPELIN-6223] Improve grammar and clarity in SECURITY-README.md for Shiro authentication

- STYLE.md
This PR updates the outdated link to Ace Editor themes in the STYLE.md file.  
The previous link pointed to a non-existing path, and the new link ensures contributors can find the correct theme list.
Documentation
[ZEPPELIN-6249](https://issues.apache.org/jira/browse/ZEPPELIN-6249)
No functional code changes. Just confirm that the updated link is valid and accessible in the rendered markdown.
_N/A_
* Does the license files need to update? No  
* Is there breaking changes for older versions? No  
> [ZEPPELIN-6249] Fix broken Ace Editor theme link in STYLE.md

- zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java
- zeppelin-server/src/main/java/org/apache/zeppelin/service/auth/AuthenticationServiceFactory.java
This PR refactors the conditional binding logic for AuthenticationService in ZeppelinServer.java.
Previously, the binding decision between ShiroAuthenticationService and NoAuthenticationService was handled via an inline if-else block.
To improve readability and maintainability, this logic has been moved to a new AuthenticationServiceFactory class that encapsulates the decision process.
This change simplifies the server initialization logic and promotes better separation of concerns.
Refactoring
* Jira: https://issues.apache.org/jira/browse/ZEPPELIN-6251
There should be no functional change.
N/A
> [ZEPPELIN-6251] Refactor AuthenticationService binding using factory method

- zeppelin-web-angular/src/app/pages/workspace/notebook-search/notebook-search.component.html
- zeppelin-web-angular/src/app/pages/workspace/notebook-search/notebook-search.component.less
- zeppelin-web-angular/src/app/pages/workspace/notebook-search/notebook-search.component.ts
- zeppelin-web-angular/src/app/pages/workspace/notebook-search/notebook-search.module.ts
Added a "no results found" message in the new Angular UI when search returns no results.
Improvement
* Add "no results found" message
https://issues.apache.org/jira/browse/ZEPPELIN-6248
> [ZEPPELIN-6248] Display a message when no search results

- elasticsearch/src/main/java/org/apache/zeppelin/elasticsearch/client/ElasticsearchClientTypeBuilder.java
This PR refactors the ElasticsearchClientTypeBuilder class to improve its robustness and readability:
- Replaces StringUtils.isEmpty() with StringUtils.isBlank() to treat whitespace-only strings as invalid input
- Simplifies enum parsing by removing redundant checks and using a try-catch block around Enum.valueOf(...)
- Ensures that invalid or null inputs gracefully fall back to ElasticsearchClientType.UNKNOWN
Refactoring
* Jira: https://issues.apache.org/jira/browse/ZEPPELIN-6262
N/A
N/A
> [ZEPPELIN-6262] Refactor ElasticsearchClientTypeBuilder for safer enum handling and blank input support

- zeppelin-web-angular/src/app/pages/workspace/share/result/result.component.ts
- zeppelin-web/src/app/notebook/paragraph/result/result.js
Fix an issue where the new Angular UI (zeppelin-web-angular) does not correctly handle carriage return (`\r`) characters. 
This causes outputs like progress bars(`#`) or status updates that use `\r` to overwrite lines to appear ugly and unnecessarily long.
This implementation is a direct port of the previous logic from the classic UI (zeppelin-web), specifically based on the original implementation in [result.controller.js](https://github.com/apache/zeppelin/blob/8ca6e57f27324b1e74fc78bea5cabd176b607408/zeppelin-web/src/app/notebook/paragraph/result/result.controller.js#L527) and [result.js](https://github.com/apache/zeppelin/blob/8ca6e57f27324b1e74fc78bea5cabd176b607408/zeppelin-web/src/app/notebook/paragraph/result/result.js#L23).
_Additionally, this update changes the behavior of the …
> [ZEPPELIN-6214] Fix new web app to handling carriage return

- influxdb/src/main/java/org/apache/zeppelin/influxdb/InfluxDBInterpreter.java
This PR refactors the `InfluxDBInterpreter.class` to improve code readability, maintainability, and adherence to modern Java practices, without altering its runtime behavior or core logic.
- Key changes include:
- Renamed getInfluxDBClient() to better reflect its purpose (e.g., getQueryApi()), improving semantic clarity.
- Removed unnecessary code
- (e.g., InterpreterContext) from methods where they are unused.
- Throwing exceptions from methods like open(), close(), cancel(), getFormType(), and getProgress() where exceptions are not thrown.
- Extracted long nested logic blocks in `internalInterpret()` into smaller, well-named private methods. 
- Replaced imperative loops with Stream operations for collection processing.
These changes aim to make the codebase more modular, clean by …
> [ZEPPELIN-6264] Refactor InfluxDBInterpreter for improved readability and maintainability

- flink/flink-scala-2.12/src/main/java/org/apache/zeppelin/flink/internal/JarHelper.java
Refactor JarHelper Class to Use a Logging Framework Instead of `System.out.println()`
Refactoring
* [here](https://issues.apache.org/jira/browse/ZEPPELIN-6267)
* Does the license files need to update? - no
* Is there breaking changes for older versions? - no
* Does this needs documentation? - no
> [ZEPPELIN-6267] Refactor JarHelper Class to Use a Logging Framework Instead of System.out.println()

- zeppelin-web-angular/src/app/share/note-create/note-create.component.html
This PR updates the label "Import As" to "Note Name" in the new note creation UI.  
The goal is to improve clarity and user experience by using a more intuitive label.  
Improvement
[ZEPPELIN-6270](https://issues.apache.org/jira/browse/ZEPPELIN-6270)
* No functional code changes
* AS-IS (Classic UI)
* AS-IS (New UI)
* TO-BE (New UI)
> [ZEPPELIN-6270] Rename "Import As" to "Note Name" for creating a new note in the new UI

- zeppelin-interpreter/src/main/java/org/apache/zeppelin/display/GUI.java
- zeppelin-interpreter/src/test/java/org/apache/zeppelin/display/GUITest.java
This PR improves the `GUI.select()` method to properly handle Collection objects passed as defaultValue. When a Collection is provided, the method now extracts the first element as the actual default value instead of using the Collection object itself.
Improvement
N/A (Minor improvement)
1. Run the test: `./mvnw test -pl zeppelin-interpreter -Dtest=GUITest`
2. Verify that the new test `testSelectWithCollectionDefault()` passes
3. The test verifies that:
- When a Collection containing `["2"]` is passed as defaultValue
- The select form uses `"2"` as the default value (not the Collection object)
* Does the license files need update? No
Currently, when using `GUI.select()` with a Collection as the …
> [ZEPPELIN-6244] Handle Collection as defaultValue in GUI.select()

- zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
This PR refactors the getNotesInfo method in NotebookService to improve readability and enforce immutability.
The functional behavior remains unchanged, but the code is now more concise and safer for multi-threaded access.
- Use `Comparator.comparing` for cleaner sorting logic
- Return an `unmodifiable list` to emphasize immutability
- Remove redundant condition for improved readability
- Refactored getNotesInfo to use inline return, eliminating intermediate variables.
This change is internal-only and does not affect any runtime behavior or public APIs.
Refactoring
* [Zeppelin-6285](https://issues.apache.org/jira/browse/ZEPPELIN-6285)
* No functional changes; existing tests should pass as-is.
* Does the license files need to update? no
* …
> [ZEPPELIN-6285] Refactor getNotesInfo to improve readability and immutability

- .gitignore
- dev/merge_zeppelin_pr.py
- dev/requirements.txt
Add .env file support and update merge script documentation
- Added .env file to .gitignore to prevent dotenv files from being tracked.
- Updated `merge_zeppelin_pr.py` to load environment variables from a .env file, enhancing configuration management.
- Added `/dev/requirements.txt` to pin Python package versions and use it for package installation.
- Revised error message for missing JIRA library to provide clearer installation instructions.
Improvement
[ZEPPELIN-6290](https://issues.apache.org/jira/browse/ZEPPELIN-6290)
* Run `uv pip install -r {REPO_ROOT}/requirements.txt`
* Environment variable configurations could be tested by adding `{REPO_ROOT}/dev/.env` file and run `merge_zeppelin_pr.py` …
> [ZEPPELIN-6290] Add .env file support and update merge script documentation

- angular/src/test/java/org/apache/zeppelin/angular/AngularInterpreterTest.java
Since there is currently no test class that can test AngularInterpreter, I added unit tests for `org.apache.zeppelin.angular.AngularInterpreter` to cover the core behavior.
- Verify interpret echoes input with Type.ANGULAR and Code.SUCCESS
- Verify empty input returns Type.ANGULAR with empty data
- Verify cancel does not throw
- Verify completion returns empty list
- Verify getFormType() returns FormType.NATIVE
- Verify getProgress() returns 0
- Verify scheduler is FIFOScheduler and name contains AngularInterpreter
Improvement
https://issues.apache.org/jira/browse/ZEPPELIN-6273
* In the angular module, run test.
> [ZEPPELIN-6273] Add unit test for AngularInterpreter

- zeppelin-web-angular/src/app/services/ticket.service.ts
This PR fixes an authentication bug where plus signs (+) in usernames or passwords were being incorrectly converted to spaces during login form submission. The issue affected both LDAP authenticator and local users in shiro.ini (IniRealm), causing authentication failures for any credentials containing URL-unsafe characters.
Bug Fix
* [ZEPPELIN-6181](https://issues.apache.org/jira/browse/ZEPPELIN-6181) : Login form does not pass plus sign into authenticator
**Manual Testing:**
1. Create a test user with username containing plus sign (e.g., `user+test`)
2. Create a test user with password containing plus sign (e.g., `pass+word`)
3. Attempt to login through the web interface
4. Verify authentication succeeds for both cases
N/A
* Does the license files need to update? **No**
* Is there …
> [ZEPPELIN-6181] Login form does not pass plus sign into authenticator

- zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java
- zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/NewNoteRequest.java
This PR renames the field 'name' to 'notePath' in the NewNoteRequest class to better reflect its purpose. The field actually represents the note's path rather than just a name, making the code more semantically clear and addressing the TODO comment that requested this change.
Refactoring
[ZEPPELIN-6307](https://issues.apache.org/jira/browse/ZEPPELIN-6307)
> [ZEPPELIN-6307] Rename fieldname in NewNoteRequest class

- docs/setup/security/shiro_authentication.md
- zeppelin-server/src/main/java/org/apache/zeppelin/realm/RoleMappingLdapRealm.java
- zeppelin-server/src/main/java/org/apache/zeppelin/service/ShiroAuthenticationService.java
- zeppelin-server/src/test/java/org/apache/zeppelin/realm/RoleMappingLdapRealmTest.java
Add configurations that allow LDAP users map directly to the role
Improvement
N/A
[ZEPPELIN-6295](https://issues.apache.org/jira/browse/ZEPPELIN-6295)
Added unit tests & compiled and tested manually.
* Does this needs documentation? Yes. And the doc has been updated.
> [ZEPPELIN-6295] Add configurations that allow LDAP users map directly to role

- zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/code-editor/code-editor.component.ts
**Description:**
You can check that in the Classic UI, word wrap is applied when editing an paragraph, but in the New UI it is not, which makes editing difficult. From a user’s perspective, the lack of word wrap can make editing both inconvenient and confusing, so this issue should be addressed. Also, in the case of .md files, word wrap is applied when the file is executed, but it is not applied when editing, which seems to cause an inconsistency.
**[Appropriate action - Classic UI]**
https://github.com/user-attachments/assets/064d883d-0b3e-44cb-9448-bc00848bae78
**[AS-IS]**
https://github.com/user-attachments/assets/3084b82a-a8fd-492f-8ef0-3fa421f92e99
**[TO-BE]**
https://github.com/user-attachments/assets/8b8db68b-9373-41d1-b091-57599b34a4f2
Bug Fix
* …
> [ZEPPELIN-6310] When paragraph to edit, word wrap doesn't work

- zeppelin-web-angular/src/app/pages/workspace/notebook/action-bar/action-bar.component.ts
**Description:**
Changing the interpreter for a paragraph did not update the binding list area when clicking the `Interpreter Binding` button in the **action bar**. Although the server had the correct values, the client did not call the update function.
**[Appropriate action - Classic UI]**
https://github.com/user-attachments/assets/f2bbb602-056f-4f09-8015-e0268233f246
**[AS-IS]**
https://github.com/user-attachments/assets/38b41567-eccd-47b6-942d-afa603d86dff
**[TO-BE]**
https://github.com/user-attachments/assets/b9959eb8-5408-49fb-a9e5-15a725ca048a
Bug Fix
* [[ZEPPELIN-6304](https://issues.apache.org/jira/browse/ZEPPELIN-6304)]
> [ZEPPELIN-6304] Changes to interpreter bindings are not reflected when reopening the binding settings

- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterSetting.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/SessionConfInterpreter.java
This PR was created to prevent an error that occurs in the `InterpreterSetting.getInterpreterGroup` method when `groupId` is null and is retrieved from the Set.
Normally, the groupId parameter does not seem to be passed as null.
I found it when tested service shutdown(#4965).
Improvement
https://issues.apache.org/jira/browse/ZEPPELIN-6282
> [ZEPPELIN-6282] Add null check condition

- zeppelin-web-angular/src/app/pages/workspace/notebook/notebook.component.html
- zeppelin-web-angular/src/app/pages/workspace/notebook/notebook.component.ts
- zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/code-editor/code-editor.component.ts
- zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/control/control.component.ts
- zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/paragraph.component.html
- zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/paragraph.component.ts
- zeppelin-web-angular/src/app/services/shortcut.service.ts
- zeppelin-web/src/app/notebook/paragraph/paragraph-control.html
Unlike the Classic UI, the New UI either lacked implementations for several shortcuts or had shortcuts assigned differently from the Classic UI. I consider this a significant issue, and after addressing other related derivative issues, I am finally submitting it.
[AS-IS]
[TO-BE]
Fixed an issue where the top area increased by 33px when search was activated. <- [referece](https://github.com/microsoft/monaco-editor/blob/5a7ba61be909ae9e4889768a3453ebb0dec392e2/monaco-editor/typedoc/monaco.d.ts#L3473)
When performing "Move Paragraph Up" or "Move Paragraph Down," the paragraph moves up or down after receiving `PARAGRAPH_MOVED`. During this process, focus was being skipped, so I added it.
In the New UI, we use the Monaco editor, where reserved shortcuts had to be explicitly overridden. I added …
> [ZEPPELIN-6197/6229] Fixed the shortcuts in the New UI so that they match the Classic UI and work correctly

- java/src/main/java/org/apache/zeppelin/java/StaticRepl.java
- java/src/test/java/org/apache/zeppelin/java/JavaInterpreterTest.java
- ToolProvider.getSystemJavaCompiler() can return null in JRE environments.
- Added a fail-fast null check in StaticRepl to throw a clear exception early.
- Updated unit test to reflect this behavior.
Bug Fix
* [ZEPPELIN-6306](https://issues.apache.org/jira/browse/ZEPPELIN-6306)
*  Run the existing unit test `testJDKCompilerAvailability()` to ensure the compiler is available in JDK.
* Run all Zeppelin unit tests to confirm no regressions.
* Does the license files need to update? no
> [ZEPPELIN-6306] Prevent NPE in StaticRepl by fail-fast JavaCompiler check

- zeppelin-web-angular/src/app/pages/workspace/notebook/notebook.component.ts
- zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/code-editor/code-editor.component.ts
- zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/paragraph.component.ts
**Description:**
Cursor behavior in the New UI’s paragraph needs to be fixed for several cursor related actions, including double-clicking, running all above/below, adding(clone), and removing paragraphs.
When **cloneParagraph()** is called, it internally calls **addParagraph()**, which has already been tested. The same addParagraph-related code is also applied in #5044. If either PR is merged first, I will rebase accordingly. I have also confirmed that **cloneParagraph()** works correctly through #5044.
Due to timing issues, I used `setTimeout` for **removeParagraph()** and **doubleClickParagraph()**. Since this is in the UI area, it likely won’t have major side effects, but I will look into it further.
**Expected:**
- When **doubleClickParagraph()** is executed, the cursor should move …
> [ZEPPELIN-6298] Fix cursor-related issues in New UI's Paragraph

- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterInfoSaving.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterSetting.java
- zeppelin-zengine/src/main/java/org/apache/zeppelin/storage/ConfigStorage.java
Refactored the `convertPermissionsFromUsersToOwners` method in InterpreterSetting.java to improve code readability and maintainability by separating JSON parsing logic from business logic, addressing the TODO comment that identified this as "ugly code".
Refactoring
[ZEPPELIN-6309](https://issues.apache.org/jira/browse/ZEPPELIN-6309)
> [ZEPPELIN-6309] Improve method by replacing JsonObject parameter

- zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterInfoSaving.java
- zeppelin-zengine/src/test/resources/conf/interpreter.json
Tests in the `zeppelin-zengine` module were failing. The main reason was that the `interpreter.json` in test resources were invalid: the value object did not have an `id` field matching its corresponding key.
As a result, the deserialized `InterpreterSetting` instance had an auto-genarated `id` field, causing the key and value.id to be inconsistent.
Before #5063, invalid settings were simply skipped. However, after that change, they caused a NPE.
This PR fixes the invalid JSON files and adds minor validation logic in the deserialization method so that such issues can be detected early by users.
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-6335
* Check `core-modules` - `zeppelin-zengine` tests in CI
* Is there breaking changes for older …
> [ZEPPELIN-6336] Fix failing zengine tests caused by invalid interpreters.json

- pom.xml
- zeppelin-web-angular/pom.xml
- zeppelin-web/pom.xml
Moved the `node.version` and `npm.version` properties from the parent `pom.xml` to each module's `pom.xml`.
This allows `zeppelin-web` and `zeppelin-web-angular` to manage their Node/NPM versions independently.
Note: Each module installs and manages its own Node/NPM, so this change simply makes that independence explicit without adding extra maintenance burden or increasing package size.
Improvement
https://issues.apache.org/jira/browse/ZEPPELIN-6338
Check CIs if Node and npm is installed for both modules.
> [ZEPPELIN-6338] Allow separate frontend modules to use different Node/NPM versions

- .github/workflows/frontend.yml
I attempted to create a related JIRA issue, but the Apache JIRA site isn't working for an hour. Therefore, I’m proceeding without creating the issue.
Currently, our CI workflow uses browser-actions/setup-edge@v1 to install Microsoft Edge. However, this action is not allowed in the apache/zeppelin repository because only actions from approved/verified sources can be used.
To resolve this, I removed the external action and replace it with a direct installation step.
Bug Fix
- Check if CI works
> [CI-Hotfix] Remove not allowed action in Selenium test

- .github/workflows/frontend.yml
- zeppelin-web-angular/e2e/global-setup.ts
- zeppelin-web-angular/e2e/global-teardown.ts
- zeppelin-web-angular/e2e/models/login-page.ts
- zeppelin-web-angular/e2e/models/login-page.util.ts
- zeppelin-web-angular/e2e/tests/app.spec.ts
- zeppelin-web-angular/e2e/tests/login/login.spec.ts
- zeppelin-web-angular/playwright.config.ts
- zeppelin-web-angular/pom.xml
Currently, Zeppelin(zeppelin-web-angular)’s E2E authentication tests require the presence of a `shiro.ini` file to run.  
However, in certain build or CI environments, this file may not exist.  
In such cases, login tests may fail or behave unpredictably.  
To improve flexibility, the test framework should support both scenarios:  
- **Auth mode (`shiro.ini` exists)** → Run all tests, including authentication/login tests  
- **Anonymous mode (`shiro.ini` does not exist)** → Skip authentication/login tests, but run all other tests  
- Added `strategy.matrix.mode: [anonymous, auth]`
- In `auth` mode, copy `shiro.ini.template → shiro.ini`
- In `anonymous` mode, skip `shiro.ini` setup to simulate a no-auth environment
- **`global-setup.ts`**
- Added `LoginTestUtil.isShiroEnabled()` to detect …
> [ZEPPELIN-6336] Enable Conditional Login Test Based on shiro.ini Presence in Zeppelin

- zeppelin-web-angular/projects/zeppelin-visualization/src/visualization.ts
- zeppelin-web-angular/src/app/pages/workspace/share/result/result.component.ts
Visualizations are not working because the constructor arguments were passed in the wrong order.
Since using `any` made this error hard to detect, I replaced it with specific types.
(Related to #5053)
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-6327
> [ZEPPELIN-6327] Fix wrong order of the arguments for Visualization components
