apache/zeppelin

docs/interpreter/neo4j.md, neo4j/pom.xml, neo4j/src/main/java/org/apache/zeppelin/graph/neo4j/Neo4jCypherInterpreter.java, neo4j/src/test/java/org/apache/zeppelin/graph/neo4j/Neo4jCypherInterpreterTest.java
=> Revert "[ZEPPELIN-3882] Neo4jInterpreter - Support Point and Date Types"

docs/usage/interpreter/overview.md
Minor update to fix punctuation-related typos in docs/usage/interpreter/overview.md
Documentation
=> docs: fix punctuation

.travis.yml, zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/SparkIntegrationTest.java, zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/SparkIntegrationTestPt1.java, zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/SparkIntegrationTestPt2.java
Fix Travis profiles and tests to archive build time under 50 minutes. 
[Improvement]
*  [ZEPPELIN-3957]
* Travis CI pass
* Does the licenses files need update? no
=> [ZEPPELIN-3957] Divide SparkIntegrationTest into parts for build under 50 minutes

docs/setup/security/shiro_authentication.md
doc update
[Documentation]
https://issues.apache.org/jira/browse/ZEPPELIN-4026
* Does the licenses files need update? N
=> [ZEPPELIN-4026] document anonymous access

zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java, zeppelin-server/src/main/java/org/apache/zeppelin/server/ZeppelinServer.java, zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java, zeppelin-server/src/test/java/org/apache/zeppelin/service/NotebookServiceTest.java, zeppelin-server/src/test/java/org/apache/zeppelin/socket/NotebookServerTest.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Note.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/CronJob.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/NoSchedulerService.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/QuartzSchedulerService.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/scheduler/SchedulerService.java, zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
Making cronjob disabled by configuration clearly. This is the first step to clear code only. In the later step, I'll make a PR because it might not be that simple.
[Refactoring]
* No
* CI
=> [MINOR] Refactor CronJob class

jdbc/pom.xml, pom.xml, rlang/pom.xml, sap/pom.xml
This PR updates the httpClient version to 4.5.13
[Refactoring]
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5633
* CI
=> [ZEPPELIN-5633] Update httpClient version

docs/usage/rest_api/notebook.md, zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java, zeppelin-server/src/main/java/org/apache/zeppelin/rest/message/CheckpointNoteRequest.java, zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java, zeppelin-server/src/test/java/org/apache/zeppelin/rest/NotebookRestApiTest.java
This PR is to provide REST API about notebook version control
[Feature]
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5663
* CI passed
=> [ZEPPELIN-5663] Provide REST API about notebook version control

.github/workflows/frontend.yml, zeppelin-integration/pom.xml, zeppelin-web/e2e/collaborativeMode.spec.js, zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncher.java
Frontend CI is consistently failed for a long time. I'd like to fix them or workaround them in this PR.
* Collaborative mode tests are failed. I disable this test temporarily, and create ticket for later fix https://issues.apache.org/jira/browse/ZEPPELIN-5674), I don't know how to fix it and seems no one is maintaining this feature.
* Spark selenium test is failed. The root cause is that env `SPARK_HOME` is not passed correctly. I fixed it in this PR.
[Bug Fix ]
* (https://issues.apache.org/jira/browse/ZEPPELIN-5670)
* CI pass
=> [ZEPPELIN-5670] Frontend CI fails

pom.xml, zeppelin-distribution/src/bin_license/LICENSE
https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on shows the CVE
Related to https://issues.apache.org/jira/browse/ZEPPELIN-5684
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5684
=> [ZEPPELIN-5684] bouncycastle 1.68

zeppelin-plugins/launcher/docker/pom.xml, zeppelin-zengine/pom.xml
more changes associated with updating commons-compress version (CVEs)
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5683
=> [ZEPPELIN-5683] further update commons-compress dependency

docs/interpreter/jdbc.md, jdbc/pom.xml
[ZEPPELIN-5696] postgresql 42.3.3
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN/ZEPPELIN-5696
=> [ZEPPELIN-5696] postgresql 42.3.3

zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java
This PR corrects the code so that the Home Note feature works again.
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5701
* Manuel tested, the CI doesn't cover this part of code
=> [ZEPPELIN-5701] Correct homeNote

.github/PULL_REQUEST_TEMPLATE
* Fix typo
* Change the list of types so that users can delete others easily
[Documentation]
N/A
* Make a new PR :-)
=> MINOR Fix typo and change some fields of PR template

.github/workflows/core.yml, .github/workflows/frontend.yml
Cache .spark-dist when running GitHub actions
[Improvement]
N/A
Check the CI skipping downloading for some spark distribution
=> MINOR Cache .spark-dist for Github actions

.github/workflows/frontend.yml
Removing unused profile
```
Warning:  The requested profile "hadoop2" could not be activated because it does not exist.
```
Bug Fix
* N/A
* Check. the CI
=> [MINOR] Remove unused profile from actions

docs/quickstart/docker.md, docs/quickstart/yarn.md
The title `Zeppelin on Yarn` is somewhat misleading. It should be consistent with the other title `Zeppelin Interpreter on Docker`.
Also fix a small syntax problem in the docs.
Documentation
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5731
* CI passed.
*  
=> [ZEPPELIN-5731] DOCS:  The title `Zeppelin on Yarn` is somewhat misleading.  

.github/workflows/core.yml, docs/interpreter/flink.md, flink/flink-scala-parent/pom.xml, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/TableEnvFactory.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/internal/ScalaShellStreamEnvironment.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/sql/AbstractStreamSqlJob.java, flink/flink-scala-parent/src/main/scala/org/apache/zeppelin/flink/FlinkScalaInterpreter.scala, flink/flink-scala-parent/src/main/scala/org/apache/zeppelin/flink/internal/FlinkILoop.scala, flink/flink-shims/src/main/java/org/apache/zeppelin/flink/FlinkShims.java, flink/flink1.12-shims/src/main/java/org/apache/zeppelin/flink/Flink112Shims.java, flink/flink1.14-shims/src/main/java/org/apache/zeppelin/flink/Flink114Shims.java, flink/flink1.15-shims/pom.xml, flink/flink1.15-shims/src/main/java/org/apache/zeppelin/flink/Flink115Shims.java, flink/flink1.15-shims/src/main/java/org/apache/zeppelin/flink/Flink115SqlInterpreter.java, flink/flink1.15-shims/src/main/java/org/apache/zeppelin/flink/PrintUtils.java, flink/flink1.15-shims/src/main/java/org/apache/zeppelin/flink/TimestampStringUtils.java, flink/flink1.15-shims/src/main/java/org/apache/zeppelin/flink/shims115/CollectStreamTableSink.java, flink/pom.xml, testing/env_python_3_with_flink_115.yml, zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/ZeppelinFlinkClusterTest115.java, zeppelin-plugins/launcher/flink/src/main/java/org/apache/zeppelin/interpreter/launcher/FlinkInterpreterLauncher.java
This PR is to support Flink 1.15 in Zeppelin.
* One module `flink1.15-shims` is introduced. Most of the flink 1.15 specific code is in this module.
* Only scala 2.12 is supported for Flink 1.15
* Flink 1.15 has changed its binary distribution, user need to do extra configuration(See `flink.md`)
[Feature ]
*https://issues.apache.org/jira/browse/ZEPPELIN-5600
* CI is passed, and manually tested flink 1.15
=> [ZEPPELIN-5600] Support Flink 1.15

zeppelin-plugins/launcher/k8s-standard/src/main/java/org/apache/zeppelin/interpreter/launcher/K8sRemoteInterpreterProcess.java, zeppelin-plugins/launcher/k8s-standard/src/main/java/org/apache/zeppelin/interpreter/launcher/K8sUtils.java, zeppelin-plugins/launcher/k8s-standard/src/test/java/org/apache/zeppelin/interpreter/launcher/K8sUtilsTest.java
This PR improves the Pod name
- Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5712
* CI
Before:
After:
=> [ZEPPELIN-5712] Improve Interpreter Pod name

zeppelin-server/src/main/java/org/apache/zeppelin/rest/NotebookRestApi.java, zeppelin-server/src/test/java/org/apache/zeppelin/service/ShiroAuthenticationServiceTest.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/AuthorizationService.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NoteAuth.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NotebookAuthorizationInfoSaving.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Paragraph.java, zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NoteAuthTest.java
This pull request adds tests for NoteAuth and polish up NoteAuth
- Refactoring
* https://issues.apache.org/jira/browse/ZEPPELIN-5750
* via CI
=> [ZEPPELIN-5750] Add tests and polish NoteAuth

Dockerfile, zeppelin-web/package.json
This pull requests use profile spark-3.2, limits the memory usage of Maven and and reduces the Maven output.
This pull request also improves the dependency resolution for angular-viewport-watch.
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5753
* manual 
=> [ZEPPELIN-5753] Improve Docker build

conf/zeppelin-site.xml.template, docs/setup/operation/configuration.md, zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
Provide config to disable version control.
Feature
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5724
* CI passed
=> [ZEPPELIN-5724] Provide config to disable version control.

zeppelin-web/package-lock.json, zeppelin-web/package.json, zeppelin-web/src/app/app.js
* Update `rimraf` and `scrollmonitor` to the latest version and fix errors that occur while building on Windows
Bug Fix
* Update rimrat/scrollmonitor versions and fix related file
* [ZEPPELIN-5767](https://issues.apache.org/jira/browse/ZEPPELIN-5767)
* CI
=> [ZEPPELIN-5767] Update rimraf and scrollmonitor to the latest version

.gitattributes
Create .gitattributes file in root path
Bug Fix
[ZEPPELIN-3945](https://issues.apache.org/jira/browse/ZEPPELIN-3945)
success when build in windows
=> [ZEPPELIN-3945] Create .gitattributes

flink/pom.xml, testing/env_python_3_with_flink_115.yml
Trivial PR to support Flink 1.15.1
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5761
* CI pass
=> [ZEPPELIN-5761] Support flink 1.15.1

zeppelin-plugins/notebookrepo/s3/pom.xml
This small PR fix the enforcer plugin.
- Hot Fix
* CI
=> HOTFIX - fix s3 enforcer

zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/InterpreterSettingManager.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Note.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NotebookImportDeserializer.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Paragraph.java
This PR fixes the non-equal behavior of the InterpreterNotFoundException. It is tried to avoid duplicate codes.
Bug Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-5780
* CI
=> [ZEPPELIN-5780] Unify paragraph errors

.github/workflows/core.yml, livy/pom.xml
livy interpreter version upgrade
Improvement
(https://issues.apache.org/jira/browse/ZEPPELIN-4871)
- CI should pass
=> [ZEPPELIN-4871] Update Livy interpreter to 0.7.1

docs/setup/storage/configuration_storage.md, docs/setup/storage/notebook_storage.md
Add documentation for Configuration Storage
Documentation
https://issues.apache.org/jira/browse/ZEPPELIN-5801
* Does the licenses files need to update? no
* Does this needs documentation? yes
=> [ZEPPELIN-5801] Add documentation for Configuration Storage

docs/setup/security/shiro_authentication.md
Remove one `ldapRealm.contextFactory.authenticationMechanism`
Documentation
=> [Hotfix] Typo in shiro_authentication.md

.asf.yaml
This provide dismiss feature when changing code after getting approval.
Improvement
* Does the licenses' files need to update? No
=> [MINOR] Add some GitHub features for PR

docs/interpreter/jdbc.md, docs/quickstart/sql_with_zeppelin.md, jdbc/src/main/java/org/apache/zeppelin/jdbc/JDBCInterpreter.java
Give an example to use Apache Kyuubi in JDBC interpreter.
Documentation
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5694
* CI passed
=> [ZEPPELIN-5694] Support apache kyuubi

zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/ParagraphTest.java
This pull request activates and corrects the test ParagraphTestcredentialReplacement()
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5826
* CI
=> [ZEPPELIN-5826] Activate credentialReplacement test

zeppelin-client-examples/pom.xml, zeppelin-client/pom.xml, zeppelin-distribution/src/bin_license/LICENSE, zeppelin-interpreter-integration/pom.xml, zeppelin-zengine/pom.xml
This PR removes unnecessary Maven dependency calls and deposits the same NPM library as dependency, which is also used to build Zeppelin NPM projects.
- Refactoring
* https://issues.apache.org/jira/browse/ZEPPELIN-5843
* CI
* Does the licenses files need to update? Yes
=> [ZEPPELIN-5843] Miscellaneous polishing

zeppelin-interpreter/src/main/java/org/apache/zeppelin/cluster/ClusterManager.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/cluster/ClusterManagerServer.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/cluster/ClusterMonitor.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/cluster/meta/ClusterMeta.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/cluster/meta/ClusterMetaEntity.java, zeppelin-interpreter/src/test/java/org/apache/zeppelin/cluster/ClusterMultiNodeTest.java, zeppelin-interpreter/src/test/java/org/apache/zeppelin/cluster/ClusterSingleNodeTest.java, zeppelin-plugins/launcher/cluster/src/main/java/org/apache/zeppelin/interpreter/launcher/ClusterInterpreterCheckThread.java, zeppelin-plugins/launcher/cluster/src/main/java/org/apache/zeppelin/interpreter/launcher/ClusterInterpreterLauncher.java, zeppelin-plugins/launcher/cluster/src/test/java/org/apache/zeppelin/interpreter/launcher/ClusterInterpreterLauncherTest.java, zeppelin-plugins/launcher/cluster/src/test/java/org/apache/zeppelin/interpreter/launcher/ClusterMockTest.java, zeppelin-server/src/main/java/org/apache/zeppelin/rest/ClusterRestApi.java, zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterIntpSettingEventListenerTest.java, zeppelin-server/src/test/java/org/apache/zeppelin/cluster/ClusterNoteEventListenerTest.java
This PR polishes the cluster code.
- Refactoring
* https://issues.apache.org/jira/browse/ZEPPELIN-5845
* CI
=> [ZEPPELIN-5845] polish Cluster classes

file/pom.xml, pom.xml, zeppelin-display/pom.xml, zeppelin-integration/pom.xml, zeppelin-interpreter-shaded/pom.xml, zeppelin-interpreter/pom.xml
This PR unifies the Maven plugin usage.
- Refactoring
* https://issues.apache.org/jira/browse/ZEPPELIN-5842
* CI
=> [ZEPPELIN-5842] Maven-Plugin management

flink/flink-scala-parent/pom.xml, hbase/pom.xml, pom.xml, spark/interpreter/pom.xml, zeppelin-client-examples/pom.xml, zeppelin-client/pom.xml, zeppelin-common/pom.xml, zeppelin-display/pom.xml, zeppelin-examples/zeppelin-example-clock/pom.xml, zeppelin-examples/zeppelin-example-horizontalbar/pom.xml, zeppelin-examples/zeppelin-example-spell-echo/pom.xml, zeppelin-examples/zeppelin-example-spell-flowchart/pom.xml, zeppelin-examples/zeppelin-example-spell-markdown/pom.xml, zeppelin-examples/zeppelin-example-spell-translator/pom.xml, zeppelin-integration/pom.xml, zeppelin-interpreter-integration/pom.xml, zeppelin-interpreter-parent/pom.xml, zeppelin-interpreter/pom.xml, zeppelin-jupyter/pom.xml, zeppelin-plugins/launcher/k8s-standard/pom.xml, zeppelin-plugins/notebookrepo/gcs/pom.xml, zeppelin-plugins/pom.xml, zeppelin-server/pom.xml, zeppelin-zengine/pom.xml, zeppelin-zengine/src/test/java/org/apache/zeppelin/util/UtilTest.java
1. Upgrade junit 4 to 5, then we can write junit 5 tests and migrate junit 4 tests to 5.
2. Run the existing junit 4 tests on Junit 5 engine.
3. Refactor `zeppelin-zengine/src/test/java/org/apache/zeppelin/util/UtilTest.java`  with jUnit 5 as an example.
[Improvement]
* Open an issue on Jira https://issues.apache.org/jira/browse/ZEPPELIN-5612
CI pass
=> [ZEPPELIN-5612] Upgrade junit 4 to 5

neo4j/pom.xml, pom.xml, spark/interpreter/pom.xml, spark/pom.xml, zeppelin-examples/pom.xml, zeppelin-integration/pom.xml, zeppelin-interpreter-parent/pom.xml, zeppelin-plugins/launcher/cluster/pom.xml, zeppelin-plugins/launcher/docker/pom.xml, zeppelin-plugins/launcher/flink/pom.xml, zeppelin-plugins/launcher/k8s-standard/pom.xml, zeppelin-plugins/launcher/yarn/pom.xml, zeppelin-web/pom.xml
This pull request removes unnecessary Maven calls, which are already configured from the apache parent pom.
enforcer maven-version goal: 
https://github.com/apache/maven-apache-parent/blob/2c37c34d2c67f7cb3e5eb7a8df0a4779e676b5b0/pom.xml#L335-L350
remote-resources-plugin:
https://github.com/apache/maven-apache-parent/blob/2c37c34d2c67f7cb3e5eb7a8df0a4779e676b5b0/pom.xml#L317-L334
And a minor renaming of an enforcer rule to make possible errors clearer.
- Refactoring
* https://issues.apache.org/jira/browse/ZEPPELIN-5847
* CI
=> [ZEPPELIN-5847] Polish Maven tasks

.github/workflows/core.yml, .github/workflows/frontend.yml, .github/workflows/quick.yml, livy/README.md, pom.xml, zeppelin-interpreter/pom.xml
* Deactivate apache-rat by default and change some CI settings
* Move git-commit-id-plugin under `zeppelin-interpreter`
Improvement
N/A
CI passed
We cannot see two plugins anymore in root pom
=> [MINOR] Polish maven plugins for root pom

.github/workflows/core.yml, .github/workflows/frontend.yml, .github/workflows/quick.yml
This small PR uses a Maven CLI option instead of a logger adjustment to suppress download output.
- Refactoring
* CI
=> [MINOR] Use Maven CLI option instead of a logger adjustment.

alluxio/pom.xml, alluxio/src/main/java/org/apache/zeppelin/alluxio/AlluxioInterpreter.java, alluxio/src/test/java/org/apache/zeppelin/alluxio/AlluxioInterpreterTest.java
[ZEPPELIN-5859] Upgrading alluxio client library to latest stable release 2.9.0
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5859
Unit Tests should validate the same
=> [ZEPPELIN-5859] Upgrading alluxio client library to latest stable release 2.9.0

.github/PULL_REQUEST_TEMPLATE
Fix type. Grammarly indicates red always...
Bug Fix
N/A
=> [MINOR] Fix tiny typo

docs/interpreter/jdbc.md, docs/quickstart/sql_with_zeppelin.md
This PR is proposes to remove incubating from Kyuubi reference, since the ASF board has approved a resolution to graduate Kyuubi into a full Top Level Project. 
https://github.com/apache/kyuubi/issues/4020
Documentation
https://issues.apache.org/jira/browse/ZEPPELIN-5869
It's docs only change.
=> [ZEPPELIN-5869] Remove Incubating from Kyuubi reference

.github/workflows/core.yml, .github/workflows/frontend.yml, .github/workflows/quick.yml
This is a trivial PR which updates the CI actions. 
- Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5873
* With current CI
=> [ZEPPELIN-5873] Update github actions

.github/workflows/core.yml, .github/workflows/frontend.yml
Current CI fails everytime. It's already reported conda-incubator/setup-miniconda#274
Hot Fix
N/A
* CI passes
=> [HOTFIX] Github Actions workaround

.github/workflows/core.yml
#4550 contains a small typo.
Typo
* CI
=> [Typo] Correct small typo

.github/workflows/core.yml, .github/workflows/frontend.yml, .github/workflows/quick.yml
I don't know when I missed it but the syntax was wrong in my lastest PR for github action #4529. It fixes this error referenced by https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
Bug Fix
N/A
* Open Dependabot issue
* @dependabot rebase
* Check how many jobs are created
=> [MINOR] Fix wrong format for github actions of 'branches-ignore'

docs/usage/display_system/basic.md
Document that the markdown display system exists
Improvement
Documentation
None
There is no Jira issue for this improvement
You could generate the documentation with this change
=> [MINOR] document 'markdown' display system

flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/ApplicationModeExecutionEnvironment.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/FlinkInterpreter.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/FlinkSqlInterpreter.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/IPyFlinkInterpreter.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/JobManager.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/PyFlinkInterpreter.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/TableEnvFactory.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/internal/JarHelper.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/internal/ScalaShellEnvironment.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/sql/AbstractStreamSqlJob.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/sql/AppendStreamSqlJob.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/sql/SingleRowStreamSqlJob.java, flink/flink-scala-parent/src/main/java/org/apache/zeppelin/flink/sql/UpdateStreamSqlJob.java, spark/interpreter/src/main/java/org/apache/zeppelin/spark/PySparkInterpreter.java, spark/interpreter/src/main/java/org/apache/zeppelin/spark/SparkInterpreter.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/SingleRowInterpreterResult.java, zeppelin-interpreter/src/test/java/org/apache/zeppelin/interpreter/SingleRowInterpreterResultTest.java
Just a little polish pull request, for classes I passed during #4545.
- Refactoring
* https://issues.apache.org/jira/browse/ZEPPELIN-5874
* CI
=> [ZEPPELIN-5874] polish flink code base

.github/workflows/core.yml
This PR removes an unnecessary cache suffix
Bug Fix
* CI
=> [MINOR] Remove conda cache suffix

zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/AuthorizationService.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java
Method contains useless variables
Improvement
* [ZEPPELIN-5891]
=> [ZEPPELIN-5891] Method contains useless variables

docs/interpreter/flink.md
Update the Flink interpreter documentation to adapt with Flink 1.16 and above
Documentation
* Manually tested with Flink 1.16.1
=> [MINOR] Update doc for flink 1.16

zeppelin-web/src/app/notebook/paragraph/result/result.controller.js
This pull request fix the bug of download csv data error
Bug Fix
https://issues.apache.org/jira/browse/ZEPPELIN-5898
* CI
=> [ZEPPELIN-5898]fix:download csv data error

flink/flink-scala-parent/pom.xml
Currently no longer in use, so the dependency is removed.
See: https://github.com/apache/zeppelin/pull/4508#issuecomment-1598025256
Bug Fix
Refactoring
* CI
=> Remove ivy and oro as flink dependency

.github/workflows/core.yml, spark/interpreter/pom.xml, spark/interpreter/src/test/java/org/apache/zeppelin/spark/SparkSqlInterpreterTest.java, spark/spark-shims/src/main/java/org/apache/zeppelin/spark/SparkVersion.java, zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/SparkIntegrationTest34.java, zeppelin-interpreter-integration/src/test/java/org/apache/zeppelin/integration/ZeppelinSparkClusterTest34.java
Simple PR to support Spark 3.4
Feature
https://issues.apache.org/jira/browse/ZEPPELIN-5902
* Add new test for Spark 3.4 and CI is passed
=> [ZEPPELIN-5902] Support Spark 3.4

jdbc/src/main/java/org/apache/zeppelin/jdbc/JDBCInterpreter.java
logging JDBC connection properties would expose password info in log file which might cause security problem
Hot Fix
* Does the license files need to update? no
=> [HOTFIX] avoid password leaks

.gitignore, zeppelin-plugins/launcher/cluster/src/main/java/org/apache/zeppelin/interpreter/launcher/ClusterInterpreterLauncher.java, zeppelin-plugins/launcher/docker/src/main/java/org/apache/zeppelin/interpreter/launcher/DockerInterpreterProcess.java, zeppelin-plugins/launcher/docker/src/test/java/org/apache/zeppelin/interpreter/launcher/DockerInterpreterProcessTest.java
Fixed minor issues in Java files formatting to make maven-checkstyle-plugin happy
Improvement
* Regular regressions tests
No license updates, no breaking changes, no need for extra docs.
=> Fixed minor formatting issues preventing the full build

.github/workflows/core.yml, .github/workflows/frontend.yml, .github/workflows/quick.yml, cassandra/src/test/java/org/apache/zeppelin/cassandra/CassandraInterpreterTest.java, flink/flink-scala-parent/pom.xml, flink/flink1.13-shims/pom.xml, flink/flink1.14-shims/pom.xml, flink/flink1.15-shims/pom.xml, flink/flink1.16-shims/pom.xml, spark/interpreter/pom.xml, spark/spark-scala-parent/pom.xml, zeppelin-display/pom.xml, zeppelin-plugins/notebookrepo/s3/pom.xml, zeppelin-zengine/src/test/java/org/apache/zeppelin/interpreter/launcher/SparkInterpreterLauncherTest.java
This PR adds JDK 11 in the CI.
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5207
* CI
=> [ZEPPELIN-5207] Build with JDK 11 in CI

cassandra/pom.xml, cassandra/src/test/java/org/apache/zeppelin/cassandra/CassandraInterpreterTest.java, cassandra/src/test/java/org/apache/zeppelin/cassandra/InterpreterLogicTest.java
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5955
* CI
=> [ZEPPELIN-5955] migrate cassandra to Junit5

mongodb/src/test/java/org/apache/zeppelin/mongodb/MongoDbInterpreterTest.java
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5952
* CI
=> [ZEPPELIN-5952] migrate mongodb to Junit5

neo4j/pom.xml, neo4j/src/test/java/org/apache/zeppelin/graph/neo4j/Neo4jCypherInterpreterTest.java, pom.xml
Part of  #4641
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5949
* CI
=> [ZEPPELIN-5949] Update testcontainers and migrate neo4j to Junit5

markdown/src/test/java/org/apache/zeppelin/markdown/FlexmarkParserTest.java, markdown/src/test/java/org/apache/zeppelin/markdown/Markdown4jParserTest.java, markdown/src/test/java/org/apache/zeppelin/markdown/MarkdownTest.java
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5961
=> [ZEPPELIN-5961] migrate markdown interpreter to JUnit5

submarine/pom.xml, submarine/src/test/java/org/apache/zeppelin/submarine/BaseInterpreterTest.java, submarine/src/test/java/org/apache/zeppelin/submarine/HdfsClientTest.java, submarine/src/test/java/org/apache/zeppelin/submarine/JinjaTemplatesTest.java, submarine/src/test/java/org/apache/zeppelin/submarine/PySubmarineInterpreterTest.java, submarine/src/test/java/org/apache/zeppelin/submarine/SubmarineInterpreterTest.java, submarine/src/test/java/org/apache/zeppelin/submarine/SubmarineJobTest.java, submarine/src/test/java/org/apache/zeppelin/submarine/YarnClientTest.java
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5960
* Ci
=> [ZEPPELIN-5960] migrate submarine to JUnit5

shell/src/test/java/org/apache/zeppelin/shell/BaseInterpreterTest.java, shell/src/test/java/org/apache/zeppelin/shell/ShellInterpreterTest.java, shell/src/test/java/org/apache/zeppelin/shell/TerminalInterpreterTest.java
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5958
* CI
=> [ZEPPELIN-5958] Migrate shell to JUnit5

livy/src/test/java/org/apache/zeppelin/livy/LivyInterpreterIT.java, livy/src/test/java/org/apache/zeppelin/livy/LivySQLInterpreterTest.java
Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-5959
* Ci
=> [ZEPPELIN-5959] migrate livy to JUnit5

zeppelin-server/src/main/java/org/apache/zeppelin/service/ShiroAuthenticationService.java
Security - SQL Injection
* [ZEPPELIN-3725](https://issues.apache.org/jira/browse/ZEPPELIN-3725)
* No behavior change
* Existing tests passed.
* Does the license files need to update? NO
* Is there breaking changes for older versions? NO
=> [ZEPPELIN-3725] Fix SQL injection

zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/YarnAppMonitor.java
Fix the log message by adding the missing placeholder `{}`
Bug Fix
It's a minor change.
Review
=> [MINOR] Fix log message in YarnAppMonitor

docs/interpreter/jdbc.md
change postgres default username mysql_user/mysql_password to pg_user/pg_password.
Documentation
=> Update jdbc.md Change postgres username

zeppelin-interpreter/src/main/java/org/apache/zeppelin/conf/ZeppelinConfiguration.java, zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java, zeppelin-server/src/test/java/org/apache/zeppelin/rest/ZeppelinRestApiTest.java, zeppelin-zengine/src/test/java/org/apache/zeppelin/notebook/NotebookTest.java
Checking if the proper users have been set when updating note especially for corn information
Hot Fix
* N/A
* Improper cron users should be blocked
* Does this needs documentation? Maybe - Will do it with another PR.
=> [HOTFIX] Check permission when updating cron information

docs/quickstart/install.md
=> [MINOR] Change minimum java version to 11 in docs

docs/interpreter/jdbc.md
Update the outdated Kyuubi JDBC docs
https://kyuubi.readthedocs.io/en/master/client/jdbc/kyuubi_jdbc.html
Documentation
ZEPPELIN-6005
Review
=> [ZEPPELIN-6005] Update Kyuubi JDBC docs

.appveyor.yml, conf/interpreter-list, dev/change_zeppelin_version.sh, docs/usage/interpreter/installation.md, scripts/docker/zeppelin/bin/Dockerfile
I noticed some places still reference the old versions, just fixed what I noticed, also enhanced `dev/change_zeppelin_version.sh` to cover more cases.
Hot Fix
It's minor.
Review
* Does this needs documentation?  No
=> [MINOR] Fix missing changed versions

.github/workflows/core.yml, .github/workflows/frontend.yml, .github/workflows/quick.yml
This pull request updates the CI actions to the latest version.
- Improvement
* https://issues.apache.org/jira/browse/ZEPPELIN-6015
* CI
=> [ZEPPELIN-6015] Update ci-action plugins

zeppelin-web-angular/src/app/pages/workspace/notebook/action-bar/action-bar.component.ts
[[ZEPPELIN-6047](https://issues.apache.org/jira/browse/ZEPPELIN-6047)]
add necessary method so the CRON functionality could be set from the new interface
Bug Fix
=> [ZEPPELIN-6047] add setConfig method to action-bar.component.ts

zeppelin-web/package-lock.json, zeppelin-web/package.json
(reopned PR https://github.com/apache/zeppelin/pull/4785)
Overview
---
When using markdown interpreter, It supposed to support [mathematical format](https://zeppelin.apache.org/docs/latest/usage/display_system/basic.html#mathematical-expressions).
But loading MathJax(JS lib for mathematical formatting) was failed.
Background
---
In the build process of zeppelin-web project, a Grunt task named copy is used to transfer files from one directory to another. This task is important for ensuring that necessary files, particularly those within node_modules, are correctly placed where they are needed.
_(zeppelin-web/Gruntfile.js)_
However, an issue has arisen where files from the node_modules/MathJax/** directory were not being copied as expected. Upon investigation, it was found that this was due …
=> [ZEPPELIN-6046] Fix(zeppelin-web): Downgrade mathjax (3.0.0 -> 2.7.9)

zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/InterpreterContext.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/interpreter/remote/RemoteInterpreterServer.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/scheduler/AbstractScheduler.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/scheduler/ExecutorFactory.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/scheduler/FIFOScheduler.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/scheduler/Job.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/scheduler/NamedThreadFactory.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/scheduler/ParallelScheduler.java, zeppelin-interpreter/src/main/java/org/apache/zeppelin/scheduler/SchedulerFactory.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/ManagedInterpreterGroup.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/interpreter/YarnAppMonitor.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/NoteEventAsyncListener.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/notebook/Notebook.java, zeppelin-zengine/src/main/java/org/apache/zeppelin/scheduler/RemoteScheduler.java
Currently I try to fix the ability to run paragraph in parallel.
- https://github.com/apache/zeppelin/commit/debfa7fcc23d6f5ea2f0664308cdbe7eba78b419#commitcomment-142856913
- https://github.com/apache/zeppelin/pull/4582#issuecomment-2076282664
This pull request collects small changes that do not really fit this bugfix, but are useful.
Refactoring
* https://issues.apache.org/jira/browse/ZEPPELIN-6066
* CI
=> [ZEPPELIN-6066] Cleanups around Job and Scheduler

NOTICE
Update Copyright year.
Improvement
N/A
Review.
=> [MINOR][LICENSE] Update NOTICE copyright

zeppelin-server/src/main/java/org/apache/zeppelin/service/NotebookService.java, zeppelin-server/src/test/java/org/apache/zeppelin/service/NotebookServiceTest.java
1. fix the cron disabling issue where zeppelin frontend was unable to disable cron, i.e., after setting the cron, e.g., every 1m, 5m, when you change it to "None", it didn't take effect when you refresh the notebook. 
2. fixes the cron refresh issue, i.e., when you update the cron setting, it always triggered the cron with the old cron expression,  because the cron setting was refreshed before notebook  updating.
Bug Fix
https://issues.apache.org/jira/projects/ZEPPELIN/issues/ZEPPELIN-6102
1. Open Zeppelin Web UI
2. Open any Notebook
3. Click the Cron Icon
4. set any cron expression
5. refresh the notebook and see if it worked as expected
6. set it to None
7. refresh the notebook and see if it worked as expected
* Is there breaking changes for …
=> [ZEPPELIN-6102] Fix cron disabling and refresh issue

zeppelin-web-angular/src/app/pages/workspace/notebook/action-bar/action-bar.component.html, zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/control/control.component.html
I noticed that only some buttons in the first group of the action bar (highlighted in the red box in the image below) had tooltips, while others did not. To improve consistency and enhance user experience, I ensured that all buttons in the first group of the action bar display tooltips on hover.
I also considered adding tooltips to the other groups of the action bar (outside the red box), but due to the complexity of implementing this with the ng-zorro UI library, more time and investigation are needed. I aim to address this in a future update.
In addition, the paragraph controller currently lacks tooltips on its icons, which may be confusing for new users unfamiliar with Zeppelin (like myself). Without tooltips, it's unclear what each button does, leading to potential usability issues. I …
=> [ZEPPELIN-6072] Unify tooltips across action bar buttons, and add tooltips to paragraph controller

zeppelin-web-angular/pom.xml, zeppelin-web/pom.xml
tiny fix to make code cleaner
Refactoring
https://issues.apache.org/jira/browse/ZEPPELIN-6116
=> [ZEPPELIN-6116] Switch from `npm install --no-lockfile` to `npm ci`

zeppelin-web-angular/package-lock.json
`package-lock.json` content changed after performing `npm install`.
Improvement
ZEPPELIN-6110
Pass CI.
=> [ZEPPELIN-6110][FOLLOWUP] Regenerate `package-lock.json`

pom.xml, zeppelin-distribution/src/bin_license/LICENSE, zeppelin-plugins/launcher/docker/pom.xml, zeppelin-server/pom.xml, zeppelin-zengine/pom.xml
See ZEPPELIN-6169
Some CVEs in old transitive dependencies
Bug Fix
Improvement
Feature
Documentation
Hot Fix
Refactoring
=> [ZEPPELIN-6169] upgrade to bcpkix-jdk18on 1.80

zeppelin-web/src/app/notebook/notebook.controller.js, zeppelin-web/src/app/notebook/notebook.controller.test.js, zeppelin-web/src/app/notebook/paragraph/paragraph.controller.js
Fix our Build
Hot Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-6175
* CI
=> [ZEPPELIN-6175] Correction of linter errors in zeppelin-web

.github/workflows/core.yml, .github/workflows/frontend.yml, .github/workflows/quick.yml, zeppelin-plugins/notebookrepo/mongo/pom.xml, zeppelin-plugins/notebookrepo/mongo/src/test/java/org/apache/zeppelin/notebook/repo/MongoNotebookRepoTest.java
Update CI Runner to ubuntu 24.04
Hot Fix
* https://issues.apache.org/jira/browse/ZEPPELIN-6179
* CI
=> [ZEPPELIN-6179] Switch to ubuntu 24.04 for GitHub-CI workflows

STYLE.md, docs/assets/themes/zeppelin/js/search.js, docs/development/contribution/how_to_contribute_code.md, docs/development/helium/writing_application.md, docs/interpreter/groovy.md, docs/interpreter/livy.md, docs/interpreter/mahout.md, docs/interpreter/neo4j.md, docs/interpreter/python.md, docs/quickstart/explore_ui.md, docs/quickstart/install.md, docs/quickstart/kubernetes.md, docs/setup/deployment/virtual_machine.md, docs/usage/display_system/basic.md, docs/usage/other_features/cron_scheduler.md, docs/usage/rest_api/helium.md, docs/usage/rest_api/notebook.md
This PR fixes multiple typos found in markdown documentation files.
| File                                                       | Incorrect Words                       | Correction(s)                    |
|------------------------------------------------------------|----------------------------------------|----------------------------------|
| `STYLE.md`                                                 | overridden                             | override                         |
| `docs/usage/rest_api/notebook.md`                          | gernerates                             | generates                        |
| `docs/usage/rest_api/helium.md`                            | reponse                                | response                         |
| …
=> [ZEPPELIN-6198] Fix multiple typos in documentation markdown files

zeppelin-web-angular/src/app/pages/workspace/configuration/configuration.component.ts
This PR updates the new UI to display configurations in alphabetical order
Improvement
https://issues.apache.org/jira/browse/ZEPPELIN-6205
=> [ZEPPELIN-6205] Sort configurations alphabetically in new UI

jdbc/src/main/java/org/apache/zeppelin/jdbc/hive/HiveUtils.java
To address this issue, nested type casting logic has been extracted into a dedicated static method (`unwrapHiveStatement`). 
Since the immediate wrapper (like `DelegatingStatement`) in the Statement chain doesn't reliably support standard `isWrapperFor` and `unwrap(Class<T> iface)` calls (often returning `false` or throwing `SQLException` as observed in its implementation), a `while` loop is used to iteratively unwrap the underlying `DelegatingStatement` layers. 
To prevent potential infinite loops or excessive unwrapping attempts, a **`MAX_STATEMENT_UNWRAP_DEPTH`** constant has been introduced, limiting the maximum unwrapping depth. Error handling and logging have also been improved to provide clearer insights into the unwrapping process.
In `HiveStatement.class` :
```
public boolean …
```
=> [ZEPPELIN-6225] Refactor HiveStatement unwrapping for improved readability and robustness

zeppelin-web-angular/pom.xml
This PR updates zeppelin-web-angular's pom.xml to run lint during the CI workflow.
Improvement
* [ZEPPELIN-6286](https://issues.apache.org/jira/browse/ZEPPELIN/ZEPPELIN-6286)
* Check the CI results, [run-tests-in-zeppelin-web-angular](https://github.com/seung-00/zeppelin/actions/runs/17176443513/job/48732990974#logs)
=> [ZEPPELIN-6286] Add lint check to zeppelin-web-angular CI workflow

bin/common.sh, bin/zeppelin-daemon.sh
Update java version check that only allows java 11 or newer
Hot Fix
N/A
N/A
Manually tested.
=> [MINOR] Update java version check that only allows java 11 or newer

zeppelin-web-angular/src/app/pages/workspace/notebook/action-bar/action-bar.component.html, zeppelin-web-angular/src/app/pages/workspace/notebook/action-bar/action-bar.component.less, zeppelin-web-angular/src/app/pages/workspace/notebook/action-bar/action-bar.component.ts, zeppelin-web-angular/src/app/pages/workspace/notebook/notebook.component.html, zeppelin-web-angular/src/app/pages/workspace/notebook/notebook.component.ts, zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/code-editor/code-editor.component.less, zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/code-editor/code-editor.component.ts, zeppelin-web-angular/src/app/pages/workspace/notebook/paragraph/paragraph.component.ts
This PR is a re-implementation of the Search and Replace UI, a feature that was available in the Classic UI.
The core search and highlighting logic has been fully rewritten to work with the Monaco Editor, which replaces the legacy Ace Editor library. 
Feature
* [ZEPPELIN-6279](https://issues.apache.org/jira/browse/ZEPPELIN-6279)
**Manual Testing**
* Check out the PR branch and check if search and highlight feature works. 
=> [ZEPPELIN-6279] Add Search/Highlight keyword feature for Code Editor
